import { RequestDetailsDTO } from 'pmrv-api';

export const workflowLabelsMap: Partial<Record<RequestDetailsDTO['requestType'], string>> = {
  INSTALLATION_ACCOUNT_OPENING: 'Account creation',
  PERMIT_ISSUANCE: 'Permit application',
  PERMIT_SURRENDER: 'Permit surrender',
  PERMIT_TRANSFER_A: 'Permit transfer A',
  PERMIT_TRANSFER_B: 'Permit transfer B',
  PERMIT_VARIATION: 'Permit variation',
  PERMIT_REVOCATION: 'Permit revocation',
  PERMIT_NOTIFICATION: 'Permit notification',
  PERMIT_BATCH_REISSUE: 'Batch variation',
  PERMIT_REISSUE: 'Permit reissue',
  AER: 'Emissions report',
  AVIATION_AER_CORSIA: 'Emissions report CORSIA',
  DRE: 'Determination of reportable emissions',
  VIR: 'Verifier improvement report',
  AIR: 'Annual improvement report',
  DOAL: 'Determination of activity level',
  NON_COMPLIANCE: 'Non-compliance',
  BDR: 'Baseline data report',
  PERMANENT_CESSATION: 'Permanent cessation',
  EMP_ISSUANCE_UKETS: 'Emissions monitoring plan UK ETS',
  EMP_ISSUANCE_CORSIA: 'Emissions monitoring plan CORSIA',
  AVIATION_AER_UKETS: 'Emissions report UK ETS',
  AVIATION_DRE_UKETS: 'Determination of emissions',
  AVIATION_ACCOUNT_CLOSURE: 'Account closure',
  EMP_VARIATION_UKETS: 'EMP variation UK ETS',
  WITHHOLDING_OF_ALLOWANCES: 'Withholding of allowances',
  RETURN_OF_ALLOWANCES: 'Return of allowances',
  AVIATION_NON_COMPLIANCE: 'Non-compliance',
  EMP_VARIATION_CORSIA: 'EMP variation CORSIA',
  AVIATION_VIR: 'Verifier improvement report',
  INSTALLATION_AUDIT: 'Audit report',
  INSTALLATION_ONSITE_INSPECTION: 'On-site inspection',
  AVIATION_AER_CORSIA_ANNUAL_OFFSETTING: 'Annual offsetting requirements',
  AVIATION_AER_CORSIA_3YEAR_PERIOD_OFFSETTING: '3-year period offsetting requirements',
  AVIATION_DOE_CORSIA: 'Estimation of emissions',
  ALR: 'Activity level report',
  NER: 'New entrant reserve',
  EMP_BATCH_REISSUE: 'Batch variation',
  HSE_TI: 'HSE target increase',
  SYSTEM_MESSAGE_NOTIFICATION: 'System message notification',
};
