package uk.gov.pmrv.api.authorization.regulator.domain;

public enum RegulatorPermissionGroup {

    MANAGE_USERS_AND_CONTACTS,
    ADD_OPERATOR_ADMIN,
    ASSIGN_REASSIGN_TASKS,
    MANAGE_VERIFICATION_BODIES,

    REVIEW_INSTALLATION_ACCOUNT,
    
    REVIEW_PERMIT_APPLICATION,
    PEER_REVIEW_PERMIT_APPLICATION,
    
    REVIEW_PERMIT_SURRENDER,
    PEER_REVIEW_PERMIT_SURRENDER,
    
    SUBMIT_PERMIT_REVOCATION,
    PEER_REVIEW_PERMIT_REVOCATION,
    
    REVIEW_PERMIT_NOTIFICATION,
    PEER_REVIEW_PERMIT_NOTIFICATION,
    
    SUBMIT_REVIEW_PERMIT_VARIATION,
    PEER_REVIEW_PERMIT_VARIATION,

    REVIEW_PERMIT_TRANSFER,
    PEER_REVIEW_PERMIT_TRANSFER,
    
    SUBMIT_PERMIT_BATCH_REISSUE,

    REVIEW_AER,

    REVIEW_VIR,

    REVIEW_AIR,
    
    SUBMIT_DRE,
    PEER_REVIEW_DRE,
    
    SUBMIT_NON_COMPLIANCE,
    PEER_REVIEW_NON_COMPLIANCE,

    REVIEW_NER,
    PEER_REVIEW_NER,

    SUBMIT_DOAL,
    PEER_REVIEW_DOAL,

    SUBMIT_WITHHOLDING_OF_ALLOWANCES,

    PEER_REVIEW_WITHHOLDING_OF_ALLOWANCES,

    SUBMIT_RETURN_OF_ALLOWANCES,
    PEER_REVIEW_RETURN_OF_ALLOWANCES,

    //Aviation related permission groups
    REVIEW_EMP_APPLICATION,
    PEER_REVIEW_EMP_APPLICATION,
    
    SUBMIT_REVIEW_EMP_VARIATION,
    PEER_REVIEW_EMP_VARIATION,
    
    SUBMIT_EMP_BATCH_REISSUE,

    SUBMIT_AVIATION_DRE,
    
    AVIATION_ACCOUNT_CLOSURE,

    PEER_REVIEW_AVIATION_DRE,

    REVIEW_AVIATION_AER,

    REVIEW_AVIATION_VIR,

    SUBMIT_AVIATION_NON_COMPLIANCE,
    PEER_REVIEW_AVIATION_NON_COMPLIANCE,
    
}
