import { InjectionToken } from '@angular/core';
import { UntypedFormGroup } from '@angular/forms';

export const WITHHOLDING_ALLOWANCES_TASK_FORM = new InjectionToken<UntypedFormGroup>(
  'Withholding of allowances task form',
);

export type StatusKey = 'DETAILS_CHANGE' | 'WITHDRAWAL_REASON_CHANGE' | 'WITHDRAWAL_REASON_CLOSE';

export const years: number[] = [2023, 2024, 2025, 2026, 2027, 2028, 2029, 2030];

export const waReasons = [
  'ASSESSING_A_RENUNCIATION_NOTICE',
  'ASSESSING_A_SPLIT_OR_A_MERGER',
  'ASSESSING_TRANSFER_OF_AVIATION_FREE_ALLOCATION_UNDER_ARTICLE_34Q',
  'DETERMINING_APPLICATION_IN_RESPECT_OF_THE_COVID_YEAR',
  'DETERMINING_A_SURRENDER_APPLICATION',
  'INVESTIGATING_AN_ERROR_IN_AVIATION_ALLOCATION_TABLE',
  'INVESTIGATING_AN_ERROR_IN_ALLOCATION_TABLE',
  'INVESTIGATING_IF_PERSON_HAS_PERMANENTLY_CEASED_AN_AVIATION_ACTIVITY',
  'INVESTIGATING_WHETHER_AN_INSTALLATION_HAS_CEASED_OPERATION',
  'MONITORING_METHODOLOGY_PLAN_HAS_NOT_BEEN_APPROVED',
  'SURRENDER_OR_REVOCATION_NOTICE_HAS_NOT_YET_COME_INTO_EFFECT',
  'OTHER',
];
