import { AviationAerUkEtsVerificationReport } from 'pmrv-api';

export const VERIFICATION_REPORT: AviationAerUkEtsVerificationReport = {
  verificationBodyId: 1,
  verificationBodyDetails: {
    name: 'VB Company',
    accreditationReferenceNumber: '1313',
    address: {
      city: 'City',
      country: 'GR',
      line1: 'street 1',
      line2: 'street 2',
      postcode: '111 80',
    },
    emissionTradingSchemes: ['UK_ETS_AVIATION', 'EU_ETS_INSTALLATIONS', 'CORSIA', 'UK_ETS_INSTALLATIONS'],
  },
  verificationTeamDetails: {
    authorisedSignatoryName: 'authorised signatory name',
    etsAuditors: 'ets auditors',
    etsTechnicalExperts: 'ets technical experts',
    independentReviewer: 'independent reviewer',
    leadEtsAuditor: 'lead ets auditor',
    technicalExperts: 'technical experts',
  },
  verifierContact: {
    email: 'test@test.com',
    name: 'Verifier Name',
    phoneNumber: '6691423232',
  },
  etsComplianceRules: {
    monitoringPlanRequirementsMet: false,
    monitoringPlanRequirementsNotMetReason: 'reason',
    ukEtsOrderRequirementsMet: false,
    ukEtsOrderRequirementsNotMetReason: 'reason',
    detailSourceDataVerified: false,
    detailSourceDataNotVerifiedReason: 'reason',
    partOfSiteVerification: 'reason',
    controlActivitiesDocumented: false,
    controlActivitiesNotDocumentedReason: 'reason',
    proceduresMonitoringPlanDocumented: false,
    proceduresMonitoringPlanNotDocumentedReason: 'reason',
    dataVerificationCompleted: false,
    dataVerificationNotCompletedReason: 'reason',
    monitoringApproachAppliedCorrectly: false,
    monitoringApproachNotAppliedCorrectlyReason: 'reason',
    flightsCompletenessComparedWithAirTrafficData: false,
    flightsCompletenessNotComparedWithAirTrafficDataReason: 'reason',
    reportedDataConsistencyChecksPerformed: false,
    reportedDataConsistencyChecksNotPerformedReason: 'reason',
    fuelConsistencyChecksPerformed: false,
    fuelConsistencyChecksNotPerformedReason: 'reason',
    missingDataMethodsApplied: false,
    missingDataMethodsNotAppliedReason: 'reason',
    regulatorGuidanceMet: false,
    regulatorGuidanceNotMetReason: 'reason',
    nonConformities: 'NOT_APPLICABLE',
  },
  overallDecision: { type: 'VERIFIED_AS_SATISFACTORY' },
  complianceMonitoringReportingRules: {
    accuracyCompliant: true,
    accuracyNonCompliantReason: 'reason',
    completenessCompliant: true,
    completenessNonCompliantReason: 'reason',
    consistencyCompliant: true,
    consistencyNonCompliantReason: 'reason',
    comparabilityCompliant: true,
    comparabilityNonCompliantReason: 'reason',
    transparencyCompliant: true,
    transparencyNonCompliantReason: 'reason',
    integrityCompliant: true,
    integrityNonCompliantReason: 'reason',
  },
  opinionStatement: {
    fuelTypes: ['JET_KEROSENE'],
    monitoringApproachType: 'EUROCONTROL_SUPPORT_FACILITY',
    emissionsCorrect: true,
    manuallyProvidedEmissions: 'emissions',
    additionalChangesNotCovered: true,
    additionalChangesNotCoveredDetails: 'details',
    siteVisit: {
      type: 'IN_PERSON',
    },
  },
  uncorrectedMisstatements: {
    exist: true,
    uncorrectedMisstatements: [{ reference: 'reference', explanation: 'explanation', materialEffect: false }],
  },
  uncorrectedNonCompliances: {
    exist: true,
    uncorrectedNonCompliances: [{ reference: 'reference', explanation: 'explanation', materialEffect: false }],
  },
  uncorrectedNonConformities: {
    existUncorrectedNonConformities: false,
    uncorrectedNonConformities: [{ reference: 'reference', explanation: 'explanation', materialEffect: false }],
    existPriorYearIssues: true,
    priorYearIssues: [{ reference: 'reference', explanation: 'explanation' }],
  },
  safExists: false,
  emissionsReductionClaimVerification: {
    safBatchClaimsReviewed: true,
    batchReferencesNotReviewed: 'reason',
    dataSampling: 'dataSampling',
    reviewResults: 'reviewResults',
    noDoubleCountingConfirmation: 'noDoubleCountingConfirmation',
    evidenceAllCriteriaMetExist: true,
    noCriteriaMetIssues: 'noCriteriaMetIssues',
    complianceWithUkEtsRequirementsExist: true,
    notCompliedWithUkEtsRequirementsAspects: 'notCompliedWithUkEtsRequirementsAspects',
  },
  recommendedImprovements: {
    exist: true,
    recommendedImprovements: [{ reference: 'reference', explanation: 'explanation' }],
  },
  materialityLevel: {
    materialityDetails: 'details',
    accreditationReferenceDocumentTypes: ['OTHER'],
    otherReference: 'reference',
  },
  dataGapsMethodologies: {
    methodRequired: true,
    methodApproved: false,
    methodConservative: false,
    noConservativeMethodDetails: '111',
    materialMisstatementExist: true,
    materialMisstatementDetails: '222',
  },
};
