package uk.gov.pmrv.api.authorization.core.domain;

import lombok.experimental.UtilityClass;

@UtilityClass
public class PmrvPermission {

    // Installation Account Opening Application task
    public static final String PERM_INSTALLATION_ACCOUNT_OPENING_APPLICATION_REVIEW_VIEW_TASK = "PERM_INSTALLATION_ACCOUNT_OPENING_APPLICATION_REVIEW_VIEW_TASK";
    public static final String PERM_INSTALLATION_ACCOUNT_OPENING_APPLICATION_REVIEW_EXECUTE_TASK = "PERM_INSTALLATION_ACCOUNT_OPENING_APPLICATION_REVIEW_EXECUTE_TASK";
    
    // Installation Account Opening Archive task
    public static final String PERM_INSTALLATION_ACCOUNT_OPENING_ARCHIVE_VIEW_TASK = "PERM_INSTALLATION_ACCOUNT_OPENING_ARCHIVE_VIEW_TASK";
    public static final String PERM_INSTALLATION_ACCOUNT_OPENING_ARCHIVE_EXECUTE_TASK = "PERM_INSTALLATION_ACCOUNT_OPENING_ARCHIVE_EXECUTE_TASK";

    // Permit Issuance Application
    public static final String PERM_PERMIT_ISSUANCE_APPLICATION_SUBMIT_VIEW_TASK = "PERM_PERMIT_ISSUANCE_APPLICATION_SUBMIT_VIEW_TASK";
    public static final String PERM_PERMIT_ISSUANCE_APPLICATION_SUBMIT_EXECUTE_TASK = "PERM_PERMIT_ISSUANCE_APPLICATION_SUBMIT_EXECUTE_TASK";

    public static final String PERM_PERMIT_ISSUANCE_APPLICATION_REVIEW_VIEW_TASK = "PERM_PERMIT_ISSUANCE_APPLICATION_REVIEW_VIEW_TASK";
    public static final String PERM_PERMIT_ISSUANCE_APPLICATION_REVIEW_EXECUTE_TASK = "PERM_PERMIT_ISSUANCE_APPLICATION_REVIEW_EXECUTE_TASK";

    public static final String PERM_PERMIT_ISSUANCE_APPLICATION_PEER_REVIEW_VIEW_TASK = "PERM_PERMIT_ISSUANCE_APPLICATION_PEER_REVIEW_VIEW_TASK";
    public static final String PERM_PERMIT_ISSUANCE_APPLICATION_PEER_REVIEW_EXECUTE_TASK = "PERM_PERMIT_ISSUANCE_APPLICATION_PEER_REVIEW_EXECUTE_TASK";

    // Permit Surrender Application
    public static final String PERM_PERMIT_SURRENDER_APPLICATION_SUBMIT_VIEW_TASK = "PERM_PERMIT_SURRENDER_APPLICATION_SUBMIT_VIEW_TASK";
    public static final String PERM_PERMIT_SURRENDER_APPLICATION_SUBMIT_EXECUTE_TASK = "PERM_PERMIT_SURRENDER_APPLICATION_SUBMIT_EXECUTE_TASK";

    public static final String PERM_PERMIT_SURRENDER_REVIEW_VIEW_TASK = "PERM_PERMIT_SURRENDER_REVIEW_VIEW_TASK";
    public static final String PERM_PERMIT_SURRENDER_REVIEW_EXECUTE_TASK = "PERM_PERMIT_SURRENDER_REVIEW_EXECUTE_TASK";

    public static final String PERM_PERMIT_SURRENDER_PEER_REVIEW_VIEW_TASK = "PERM_PERMIT_SURRENDER_PEER_REVIEW_VIEW_TASK";
    public static final String PERM_PERMIT_SURRENDER_PEER_REVIEW_EXECUTE_TASK = "PERM_PERMIT_SURRENDER_PEER_REVIEW_EXECUTE_TASK";

    // Permit Revocation
    public static final String PERM_PERMIT_REVOCATION_SUBMIT_VIEW_TASK = "PERM_PERMIT_REVOCATION_SUBMIT_VIEW_TASK";
    public static final String PERM_PERMIT_REVOCATION_SUBMIT_EXECUTE_TASK = "PERM_PERMIT_REVOCATION_SUBMIT_EXECUTE_TASK";

    public static final String PERM_PERMIT_REVOCATION_PEER_REVIEW_VIEW_TASK = "PERM_PERMIT_REVOCATION_PEER_REVIEW_VIEW_TASK";
    public static final String PERM_PERMIT_REVOCATION_PEER_REVIEW_EXECUTE_TASK = "PERM_PERMIT_REVOCATION_PEER_REVIEW_EXECUTE_TASK";

    public static final String PERM_PERMIT_REVOCATION_MAKE_PAYMENT_VIEW_TASK = "PERM_PERMIT_REVOCATION_MAKE_PAYMENT_VIEW_TASK";
    public static final String PERM_PERMIT_REVOCATION_MAKE_PAYMENT_EXECUTE_TASK = "PERM_PERMIT_REVOCATION_MAKE_PAYMENT_EXECUTE_TASK";

    // Permit Notification Application
    public static final String PERM_PERMIT_NOTIFICATION_APPLICATION_SUBMIT_VIEW_TASK = "PERM_PERMIT_NOTIFICATION_APPLICATION_SUBMIT_VIEW_TASK";
    public static final String PERM_PERMIT_NOTIFICATION_APPLICATION_SUBMIT_EXECUTE_TASK = "PERM_PERMIT_NOTIFICATION_APPLICATION_SUBMIT_EXECUTE_TASK";

    public static final String PERM_PERMIT_NOTIFICATION_REVIEW_VIEW_TASK = "PERM_PERMIT_NOTIFICATION_REVIEW_VIEW_TASK";
    public static final String PERM_PERMIT_NOTIFICATION_REVIEW_EXECUTE_TASK = "PERM_PERMIT_NOTIFICATION_REVIEW_EXECUTE_TASK";

    public static final String PERM_PERMIT_NOTIFICATION_PEER_REVIEW_VIEW_TASK = "PERM_PERMIT_NOTIFICATION_PEER_REVIEW_VIEW_TASK";
    public static final String PERM_PERMIT_NOTIFICATION_PEER_REVIEW_EXECUTE_TASK = "PERM_PERMIT_NOTIFICATION_PEER_REVIEW_EXECUTE_TASK";
    
    //Permit Variation
    public static final String PERM_PERMIT_VARIATION_APPLICATION_SUBMIT_VIEW_TASK = "PERM_PERMIT_VARIATION_APPLICATION_SUBMIT_VIEW_TASK";
    public static final String PERM_PERMIT_VARIATION_APPLICATION_SUBMIT_EXECUTE_TASK = "PERM_PERMIT_VARIATION_APPLICATION_SUBMIT_EXECUTE_TASK";
    public static final String PERM_PERMIT_VARIATION_SUBMIT_REVIEW_VIEW_TASK = "PERM_PERMIT_VARIATION_SUBMIT_REVIEW_VIEW_TASK";
    public static final String PERM_PERMIT_VARIATION_SUBMIT_REVIEW_EXECUTE_TASK = "PERM_PERMIT_VARIATION_SUBMIT_REVIEW_EXECUTE_TASK";
    public static final String PERM_PERMIT_VARIATION_PEER_REVIEW_VIEW_TASK = "PERM_PERMIT_VARIATION_PEER_REVIEW_VIEW_TASK";
    public static final String PERM_PERMIT_VARIATION_PEER_REVIEW_EXECUTE_TASK = "PERM_PERMIT_VARIATION_PEER_REVIEW_EXECUTE_TASK";

    // AER Application
    public static final String PERM_AER_APPLICATION_SUBMIT_VIEW_TASK = "PERM_AER_APPLICATION_SUBMIT_VIEW_TASK";
    public static final String PERM_AER_APPLICATION_SUBMIT_EXECUTE_TASK = "PERM_AER_APPLICATION_SUBMIT_EXECUTE_TASK";

    public static final String PERM_AER_APPLICATION_MARK_NOT_REQUIRED_EXECUTE_TASK = "PERM_AER_APPLICATION_MARK_NOT_REQUIRED_EXECUTE_TASK";

    public static final String PERM_AER_APPLICATION_REVIEW_VIEW_TASK = "PERM_AER_APPLICATION_REVIEW_VIEW_TASK";
    public static final String PERM_AER_APPLICATION_REVIEW_EXECUTE_TASK = "PERM_AER_APPLICATION_REVIEW_EXECUTE_TASK";

    public static final String PERM_AER_APPLICATION_VERIFICATION_VIEW_TASK = "PERM_AER_APPLICATION_VERIFICATION_VIEW_TASK";
    public static final String PERM_AER_APPLICATION_VERIFICATION_EXECUTE_TASK = "PERM_AER_APPLICATION_VERIFICATION_EXECUTE_TASK";

    // VIR
    public static final String PERM_VIR_APPLICATION_SUBMIT_VIEW_TASK = "PERM_VIR_APPLICATION_SUBMIT_VIEW_TASK";
    public static final String PERM_VIR_APPLICATION_SUBMIT_EXECUTE_TASK = "PERM_VIR_APPLICATION_SUBMIT_EXECUTE_TASK";

    public static final String PERM_VIR_APPLICATION_REVIEW_VIEW_TASK = "PERM_VIR_APPLICATION_REVIEW_VIEW_TASK";
    public static final String PERM_VIR_APPLICATION_REVIEW_EXECUTE_TASK = "PERM_VIR_APPLICATION_REVIEW_EXECUTE_TASK";

    // AIR
    public static final String PERM_AIR_APPLICATION_SUBMIT_VIEW_TASK = "PERM_AIR_APPLICATION_SUBMIT_VIEW_TASK";
    public static final String PERM_AIR_APPLICATION_SUBMIT_EXECUTE_TASK = "PERM_AIR_APPLICATION_SUBMIT_EXECUTE_TASK";

    public static final String PERM_AIR_APPLICATION_REVIEW_VIEW_TASK = "PERM_AIR_APPLICATION_REVIEW_VIEW_TASK";
    public static final String PERM_AIR_APPLICATION_REVIEW_EXECUTE_TASK = "PERM_AIR_APPLICATION_REVIEW_EXECUTE_TASK";

    // Permit Transfer
    public static final String PERM_PERMIT_TRANSFER_A_APPLICATION_SUBMIT_VIEW_TASK = "PERM_PERMIT_TRANSFER_A_APPLICATION_SUBMIT_VIEW_TASK";
    public static final String PERM_PERMIT_TRANSFER_A_APPLICATION_SUBMIT_EXECUTE_TASK = "PERM_PERMIT_TRANSFER_A_APPLICATION_SUBMIT_EXECUTE_TASK";
    public static final String PERM_PERMIT_TRANSFER_B_APPLICATION_SUBMIT_VIEW_TASK = "PERM_PERMIT_TRANSFER_B_APPLICATION_SUBMIT_VIEW_TASK";
    public static final String PERM_PERMIT_TRANSFER_B_APPLICATION_SUBMIT_EXECUTE_TASK = "PERM_PERMIT_TRANSFER_B_APPLICATION_SUBMIT_EXECUTE_TASK";

    public static final String PERM_PERMIT_TRANSFER_B_REVIEW_VIEW_TASK = "PERM_PERMIT_TRANSFER_B_REVIEW_VIEW_TASK";
    public static final String PERM_PERMIT_TRANSFER_B_REVIEW_EXECUTE_TASK = "PERM_PERMIT_TRANSFER_B_REVIEW_EXECUTE_TASK";
    public static final String PERM_PERMIT_TRANSFER_B_PEER_REVIEW_VIEW_TASK = "PERM_PERMIT_TRANSFER_B_PEER_REVIEW_VIEW_TASK";
    public static final String PERM_PERMIT_TRANSFER_B_PEER_REVIEW_EXECUTE_TASK = "PERM_PERMIT_TRANSFER_B_PEER_REVIEW_EXECUTE_TASK";
    
    // Permit Batch Reissue
    public static final String PERM_PERMIT_BATCH_REISSUE_SUBMIT_VIEW_TASK = "PERM_PERMIT_BATCH_REISSUE_SUBMIT_VIEW_TASK";
    public static final String PERM_PERMIT_BATCH_REISSUE_SUBMIT_EXECUTE_TASK = "PERM_PERMIT_BATCH_REISSUE_SUBMIT_EXECUTE_TASK";
    
    // DRE
    public static final String PERM_DRE_APPLICATION_SUBMIT_VIEW_TASK = "PERM_DRE_APPLICATION_SUBMIT_VIEW_TASK";
    public static final String PERM_DRE_APPLICATION_SUBMIT_EXECUTE_TASK = "PERM_DRE_APPLICATION_SUBMIT_EXECUTE_TASK";

    public static final String PERM_DRE_PEER_REVIEW_VIEW_TASK = "PERM_DRE_PEER_REVIEW_VIEW_TASK";
    public static final String PERM_DRE_PEER_REVIEW_EXECUTE_TASK = "PERM_DRE_PEER_REVIEW_EXECUTE_TASK";

    public static final String PERM_DRE_MAKE_PAYMENT_VIEW_TASK = "PERM_DRE_MAKE_PAYMENT_VIEW_TASK";
    public static final String PERM_DRE_MAKE_PAYMENT_EXECUTE_TASK = "PERM_DRE_MAKE_PAYMENT_EXECUTE_TASK";
    
    // Non Compliance
    public static final String PERM_NON_COMPLIANCE_SUBMIT_VIEW_TASK = "PERM_NON_COMPLIANCE_SUBMIT_VIEW_TASK";
    public static final String PERM_NON_COMPLIANCE_SUBMIT_EXECUTE_TASK = "PERM_NON_COMPLIANCE_SUBMIT_EXECUTE_TASK";

    public static final String PERM_NON_COMPLIANCE_PEER_REVIEW_VIEW_TASK = "PERM_NON_COMPLIANCE_PEER_REVIEW_VIEW_TASK";
    public static final String PERM_NON_COMPLIANCE_PEER_REVIEW_EXECUTE_TASK = "PERM_NON_COMPLIANCE_PEER_REVIEW_EXECUTE_TASK";
    
    // New Entrant Reserve
    public static final String PERM_NER_SUBMIT_VIEW_TASK = "PERM_NER_SUBMIT_VIEW_TASK";
    public static final String PERM_NER_SUBMIT_EXECUTE_TASK = "PERM_NER_SUBMIT_EXECUTE_TASK";

    public static final String PERM_NER_REVIEW_VIEW_TASK = "PERM_NER_REVIEW_VIEW_TASK";
    public static final String PERM_NER_REVIEW_EXECUTE_TASK = "PERM_NER_REVIEW_EXECUTE_TASK";

    public static final String PERM_NER_PEER_REVIEW_VIEW_TASK = "PERM_NER_PEER_REVIEW_VIEW_TASK";
    public static final String PERM_NER_PEER_REVIEW_EXECUTE_TASK = "PERM_NER_PEER_REVIEW_EXECUTE_TASK";

    public static final String PERM_WITHHOLDING_OF_ALLOWANCES_SUBMIT_VIEW_TASK = "PERM_WITHHOLDING_OF_ALLOWANCES_SUBMIT_VIEW_TASK";
    public static final String PERM_WITHHOLDING_OF_ALLOWANCES_SUBMIT_EXECUTE_TASK = "PERM_WITHHOLDING_OF_ALLOWANCES_SUBMIT_EXECUTE_TASK";
    public static final String PERM_WITHHOLDING_OF_ALLOWANCES_PEER_REVIEW_VIEW_TASK = "PERM_WITHHOLDING_OF_ALLOWANCES_PEER_REVIEW_VIEW_TASK";
    public static final String PERM_WITHHOLDING_OF_ALLOWANCES_PEER_REVIEW_EXECUTE_TASK = "PERM_WITHHOLDING_OF_ALLOWANCES_PEER_REVIEW_EXECUTE_TASK";

    public static final String PERM_RETURN_OF_ALLOWANCES_SUBMIT_VIEW_TASK = "PERM_RETURN_OF_ALLOWANCES_SUBMIT_VIEW_TASK";
    public static final String PERM_RETURN_OF_ALLOWANCES_SUBMIT_EXECUTE_TASK = "PERM_RETURN_OF_ALLOWANCES_SUBMIT_EXECUTE_TASK";
    public static final String PERM_RETURN_OF_ALLOWANCES_PEER_REVIEW_VIEW_TASK = "PERM_RETURN_OF_ALLOWANCES_PEER_REVIEW_VIEW_TASK";
    public static final String PERM_RETURN_OF_ALLOWANCES_PEER_REVIEW_EXECUTE_TASK = "PERM_RETURN_OF_ALLOWANCES_PEER_REVIEW_EXECUTE_TASK";

    // DOAL
    public static final String PERM_DOAL_APPLICATION_SUBMIT_VIEW_TASK = "PERM_DOAL_APPLICATION_SUBMIT_VIEW_TASK";
    public static final String PERM_DOAL_APPLICATION_SUBMIT_EXECUTE_TASK = "PERM_DOAL_APPLICATION_SUBMIT_EXECUTE_TASK";

    public static final String PERM_DOAL_PEER_REVIEW_VIEW_TASK = "PERM_DOAL_PEER_REVIEW_VIEW_TASK";
    public static final String PERM_DOAL_PEER_REVIEW_EXECUTE_TASK = "PERM_DOAL_PEER_REVIEW_EXECUTE_TASK";

    //installation inspection
    public static final String PERM_INSTALLATION_AUDIT_APPLICATION_SUBMIT_VIEW_TASK = "PERM_INSTALLATION_AUDIT_APPLICATION_SUBMIT_VIEW_TASK";
    public static final String PERM_INSTALLATION_AUDIT_APPLICATION_SUBMIT_EXECUTE_TASK = "PERM_INSTALLATION_AUDIT_APPLICATION_SUBMIT_EXECUTE_TASK";
    public static final String PERM_INSTALLATION_AUDIT_PEER_REVIEW_VIEW_TASK = "PERM_INSTALLATION_AUDIT_PEER_REVIEW_VIEW_TASK";
    public static final String PERM_INSTALLATION_AUDIT_PEER_REVIEW_EXECUTE_TASK = "PERM_INSTALLATION_AUDIT_PEER_REVIEW_EXECUTE_TASK";
    public static final String PERM_INSTALLATION_AUDIT_OPERATOR_RESPOND_TO_FOLLOWUP_ACTIONS_VIEW_TASK = "PERM_INSTALLATION_AUDIT_OPERATOR_RESPOND_TO_FOLLOWUP_ACTIONS_VIEW_TASK";
    public static final String PERM_INSTALLATION_AUDIT_OPERATOR_RESPOND_TO_FOLLOWUP_ACTIONS_EXECUTE_TASK = "PERM_INSTALLATION_AUDIT_OPERATOR_RESPOND_TO_FOLLOWUP_ACTIONS_EXECUTE_TASK";

    public static final String PERM_INSTALLATION_ONSITE_INSPECTION_APPLICATION_SUBMIT_VIEW_TASK = "PERM_INSTALLATION_ONSITE_INSPECTION_APPLICATION_SUBMIT_VIEW_TASK";
    public static final String PERM_INSTALLATION_ONSITE_INSPECTION_APPLICATION_SUBMIT_EXECUTE_TASK = "PERM_INSTALLATION_ONSITE_INSPECTION_APPLICATION_SUBMIT_EXECUTE_TASK";
    public static final String PERM_INSTALLATION_ONSITE_INSPECTION_PEER_REVIEW_VIEW_TASK = "PERM_INSTALLATION_ONSITE_INSPECTION_PEER_REVIEW_VIEW_TASK";
    public static final String PERM_INSTALLATION_ONSITE_INSPECTION_PEER_REVIEW_EXECUTE_TASK = "PERM_INSTALLATION_ONSITE_INSPECTION_PEER_REVIEW_EXECUTE_TASK";
    public static final String PERM_INSTALLATION_ONSITE_INSPECTION_OPERATOR_RESPOND_TO_FOLLOWUP_ACTIONS_VIEW_TASK = "PERM_INSTALLATION_ONSITE_INSPECTION_OPERATOR_RESPOND_TO_FOLLOWUP_ACTIONS_VIEW_TASK";
    public static final String PERM_INSTALLATION_ONSITE_INSPECTION_OPERATOR_RESPOND_TO_FOLLOWUP_ACTIONS_EXECUTE_TASK = "PERM_INSTALLATION_ONSITE_INSPECTION_OPERATOR_RESPOND_TO_FOLLOWUP_ACTIONS_EXECUTE_TASK";


    //BDR
    public static final String PERM_BDR_APPLICATION_SUBMIT_VIEW_TASK = "PERM_BDR_APPLICATION_SUBMIT_VIEW_TASK";
    public static final String PERM_BDR_APPLICATION_SUBMIT_EXECUTE_TASK = "PERM_BDR_APPLICATION_SUBMIT_EXECUTE_TASK";
    public static final String PERM_BDR_APPLICATION_PEER_REVIEW_VIEW_TASK = "PERM_BDR_APPLICATION_PEER_REVIEW_VIEW_TASK";
    public static final String PERM_BDR_APPLICATION_PEER_REVIEW_EXECUTE_TASK = "PERM_BDR_APPLICATION_PEER_REVIEW_EXECUTE_TASK";
    public static final String PERM_BDR_APPLICATION_REGULATOR_REVIEW_SUBMIT_VIEW_TASK = "PERM_BDR_APPLICATION_REGULATOR_REVIEW_SUBMIT_VIEW_TASK";
    public static final String PERM_BDR_APPLICATION_REGULATOR_REVIEW_SUBMIT_EXECUTE_TASK = "PERM_BDR_APPLICATION_REGULATOR_REVIEW_SUBMIT_EXECUTE_TASK";
    public static final String PERM_BDR_APPLICATION_VERIFICATION_SUBMIT_VIEW_TASK = "PERM_BDR_APPLICATION_VERIFICATION_SUBMIT_VIEW_TASK";
    public static final String PERM_BDR_APPLICATION_VERIFICATION_SUBMIT_EXECUTE_TASK = "PERM_BDR_APPLICATION_VERIFICATION_SUBMIT_EXECUTE_TASK";
    public static final String PERM_BDR_APPLICATION_AMENDS_SUBMIT_EXECUTE_TASK = "PERM_BDR_APPLICATION_AMENDS_SUBMIT_EXECUTE_TASK";
    public static final String PERM_BDR_APPLICATION_AMENDS_SUBMIT_VIEW_TASK = "PERM_BDR_APPLICATION_AMENDS_SUBMIT_VIEW_TASK";

    //Permanent Cessation
    public static final String PERM_PERMANENT_CESSATION_APPLICATION_SUBMIT_VIEW_TASK = "PERM_PERMANENT_CESSATION_APPLICATION_SUBMIT_VIEW_TASK";
    public static final String PERM_PERMANENT_CESSATION_APPLICATION_SUBMIT_EXECUTE_TASK = "PERM_PERMANENT_CESSATION_APPLICATION_SUBMIT_EXECUTE_TASK";
    public static final String PERM_PERMANENT_CESSATION_PEER_REVIEW_VIEW_TASK = "PERM_PERMANENT_CESSATION_PEER_REVIEW_VIEW_TASK";
    public static final String PERM_PERMANENT_CESSATION_PEER_REVIEW_EXECUTE_TASK = "PERM_PERMANENT_CESSATION_PEER_REVIEW_EXECUTE_TASK";

    //ALR
    public static final String PERM_ALR_APPLICATION_SUBMIT_VIEW_TASK = "PERM_ALR_APPLICATION_SUBMIT_VIEW_TASK";
    public static final String PERM_ALR_APPLICATION_SUBMIT_EXECUTE_TASK = "PERM_ALR_APPLICATION_SUBMIT_EXECUTE_TASK";
    public static final String PERM_ALR_APPLICATION_VERIFICATION_SUBMIT_VIEW_TASK = "PERM_ALR_APPLICATION_VERIFICATION_SUBMIT_VIEW_TASK";
    public static final String PERM_ALR_APPLICATION_VERIFICATION_SUBMIT_EXECUTE_TASK = "PERM_ALR_APPLICATION_VERIFICATION_SUBMIT_EXECUTE_TASK";


    //EMP Issuance Application
    public static final String PERM_EMP_ISSUANCE_APPLICATION_SUBMIT_VIEW_TASK = "PERM_EMP_ISSUANCE_APPLICATION_SUBMIT_VIEW_TASK";
    public static final String PERM_EMP_ISSUANCE_APPLICATION_SUBMIT_EXECUTE_TASK = "PERM_EMP_ISSUANCE_APPLICATION_SUBMIT_EXECUTE_TASK";

    public static final String PERM_EMP_ISSUANCE_APPLICATION_REVIEW_VIEW_TASK = "PERM_EMP_ISSUANCE_APPLICATION_REVIEW_VIEW_TASK";
    public static final String PERM_EMP_ISSUANCE_APPLICATION_REVIEW_EXECUTE_TASK = "PERM_EMP_ISSUANCE_APPLICATION_REVIEW_EXECUTE_TASK";

    public static final String PERM_EMP_ISSUANCE_APPLICATION_PEER_REVIEW_VIEW_TASK = "PERM_EMP_ISSUANCE_APPLICATION_PEER_REVIEW_VIEW_TASK";
    public static final String PERM_EMP_ISSUANCE_APPLICATION_PEER_REVIEW_EXECUTE_TASK = "PERM_EMP_ISSUANCE_APPLICATION_PEER_REVIEW_EXECUTE_TASK";
    
    //EMP Variation Application
    public static final String PERM_EMP_VARIATION_APPLICATION_SUBMIT_VIEW_TASK = "PERM_EMP_VARIATION_APPLICATION_SUBMIT_VIEW_TASK";
    public static final String PERM_EMP_VARIATION_APPLICATION_SUBMIT_EXECUTE_TASK = "PERM_EMP_VARIATION_APPLICATION_SUBMIT_EXECUTE_TASK";

    public static final String PERM_EMP_VARIATION_SUBMIT_REVIEW_VIEW_TASK = "PERM_EMP_VARIATION_SUBMIT_REVIEW_VIEW_TASK";
    public static final String PERM_EMP_VARIATION_SUBMIT_REVIEW_EXECUTE_TASK = "PERM_EMP_VARIATION_SUBMIT_REVIEW_EXECUTE_TASK";

    public static final String PERM_EMP_VARIATION_PEER_REVIEW_VIEW_TASK = "PERM_EMP_VARIATION_PEER_REVIEW_VIEW_TASK";
    public static final String PERM_EMP_VARIATION_PEER_REVIEW_EXECUTE_TASK = "PERM_EMP_VARIATION_PEER_REVIEW_EXECUTE_TASK";
    
    //EMP Batch Reissue
    public static final String PERM_EMP_BATCH_REISSUE_SUBMIT_VIEW_TASK = "PERM_EMP_BATCH_REISSUE_SUBMIT_VIEW_TASK";
    public static final String PERM_EMP_BATCH_REISSUE_SUBMIT_EXECUTE_TASK = "PERM_EMP_BATCH_REISSUE_SUBMIT_EXECUTE_TASK";

    //Aviation AER
    public static final String PERM_AVIATION_AER_APPLICATION_SUBMIT_VIEW_TASK = "PERM_AVIATION_AER_APPLICATION_SUBMIT_VIEW_TASK";
    public static final String PERM_AVIATION_AER_APPLICATION_SUBMIT_EXECUTE_TASK = "PERM_AVIATION_AER_APPLICATION_SUBMIT_EXECUTE_TASK";

    public static final String PERM_AVIATION_AER_ANNUAL_OFFSETTING_APPLICATION_SUBMIT_VIEW_TASK = "PERM_AVIATION_AER_ANNUAL_OFFSETTING_APPLICATION_SUBMIT_VIEW_TASK";
    public static final String PERM_AVIATION_AER_ANNUAL_OFFSETTING_APPLICATION_SUBMIT_EXECUTE_TASK = "PERM_AVIATION_AER_ANNUAL_OFFSETTING_APPLICATION_SUBMIT_EXECUTE_TASK";

    public static final String PERM_AVIATION_AER_ANNUAL_OFFSETTING_APPLICATION_PEER_REVIEW_VIEW_TASK = "PERM_AVIATION_AER_ANNUAL_OFFSETTING_APPLICATION_PEER_REVIEW_VIEW_TASK";
    public static final String PERM_AVIATION_AER_ANNUAL_OFFSETTING_APPLICATION_PEER_REVIEW_EXECUTE_TASK = "PERM_AVIATION_AER_ANNUAL_OFFSETTING_APPLICATION_PEER_REVIEW_EXECUTE_TASK";

    public static final String PERM_AVIATION_AER_3YEAR_PERIOD_OFFSETTING_APPLICATION_SUBMIT_VIEW_TASK = "PERM_AVIATION_AER_3YEAR_PERIOD_OFFSETTING_APPLICATION_SUBMIT_VIEW_TASK";
    public static final String PERM_AVIATION_AER_3YEAR_PERIOD_OFFSETTING_APPLICATION_SUBMIT_EXECUTE_TASK = "PERM_AVIATION_AER_3YEAR_PERIOD_OFFSETTING_APPLICATION_SUBMIT_EXECUTE_TASK";
    public static final String PERM_AVIATION_AER_CORSIA_3YEAR_PERIOD_OFFSETTING_APPLICATION_PEER_REVIEW_VIEW_TASK = "PERM_AVIATION_AER_CORSIA_3YEAR_PERIOD_OFFSETTING_APPLICATION_PEER_REVIEW_VIEW_TASK";
    public static final String PERM_AVIATION_AER_CORSIA_3YEAR_PERIOD_OFFSETTING_APPLICATION_PEER_REVIEW_EXECUTE_TASK = "PERM_AVIATION_AER_CORSIA_3YEAR_PERIOD_OFFSETTING_APPLICATION_PEER_REVIEW_EXECUTE_TASK";

    public static final String PERM_AVIATION_AER_APPLICATION_VERIFICATION_VIEW_TASK = "PERM_AVIATION_AER_APPLICATION_VERIFICATION_VIEW_TASK";
    public static final String PERM_AVIATION_AER_APPLICATION_VERIFICATION_EXECUTE_TASK = "PERM_AVIATION_AER_APPLICATION_VERIFICATION_EXECUTE_TASK";

    public static final String PERM_AVIATION_AER_APPLICATION_REVIEW_VIEW_TASK = "PERM_AVIATION_AER_APPLICATION_REVIEW_VIEW_TASK";
    public static final String PERM_AVIATION_AER_APPLICATION_REVIEW_EXECUTE_TASK = "PERM_AVIATION_AER_APPLICATION_REVIEW_EXECUTE_TASK";

    // Aviation DRE
    public static final String PERM_AVIATION_DRE_APPLICATION_SUBMIT_VIEW_TASK = "PERM_AVIATION_DRE_APPLICATION_SUBMIT_VIEW_TASK";
    public static final String PERM_AVIATION_DRE_APPLICATION_SUBMIT_EXECUTE_TASK = "PERM_AVIATION_DRE_APPLICATION_SUBMIT_EXECUTE_TASK";

    public static final String PERM_AVIATION_DRE_MAKE_PAYMENT_VIEW_TASK = "PERM_AVIATION_DRE_MAKE_PAYMENT_VIEW_TASK";
    public static final String PERM_AVIATION_DRE_MAKE_PAYMENT_EXECUTE_TASK = "PERM_AVIATION_DRE_MAKE_PAYMENT_EXECUTE_TASK";

    public static final String PERM_AVIATION_DRE_PEER_REVIEW_VIEW_TASK = "PERM_AVIATION_DRE_PEER_REVIEW_VIEW_TASK";
    public static final String PERM_AVIATION_DRE_PEER_REVIEW_EXECUTE_TASK = "PERM_AVIATION_DRE_PEER_REVIEW_EXECUTE_TASK";

    // Aviation DOE CORSIA
    public static final String PERM_AVIATION_DOE_CORSIA_APPLICATION_SUBMIT_VIEW_TASK = "PERM_AVIATION_DOE_CORSIA_APPLICATION_SUBMIT_VIEW_TASK";
    public static final String PERM_AVIATION_DOE_CORSIA_APPLICATION_SUBMIT_EXECUTE_TASK = "PERM_AVIATION_DOE_CORSIA_APPLICATION_SUBMIT_EXECUTE_TASK";

    public static final String PERM_AVIATION_DOE_CORSIA_PEER_REVIEW_VIEW_TASK = "PERM_AVIATION_DOE_CORSIA_PEER_REVIEW_VIEW_TASK";
    public static final String PERM_AVIATION_DOE_CORSIA_PEER_REVIEW_EXECUTE_TASK = "PERM_AVIATION_DOE_CORSIA_PEER_REVIEW_EXECUTE_TASK";
    // Aviation VIR
    public static final String PERM_AVIATION_VIR_APPLICATION_SUBMIT_VIEW_TASK = "PERM_AVIATION_VIR_APPLICATION_SUBMIT_VIEW_TASK";
    public static final String PERM_AVIATION_VIR_APPLICATION_SUBMIT_EXECUTE_TASK = "PERM_AVIATION_VIR_APPLICATION_SUBMIT_EXECUTE_TASK";

    public static final String PERM_AVIATION_VIR_APPLICATION_REVIEW_VIEW_TASK = "PERM_AVIATION_VIR_APPLICATION_REVIEW_VIEW_TASK";
    public static final String PERM_AVIATION_VIR_APPLICATION_REVIEW_EXECUTE_TASK = "PERM_AVIATION_VIR_APPLICATION_REVIEW_EXECUTE_TASK";

    // Aviation Non Compliance
    public static final String PERM_AVIATION_NON_COMPLIANCE_SUBMIT_VIEW_TASK = "PERM_AVIATION_NON_COMPLIANCE_SUBMIT_VIEW_TASK";
    public static final String PERM_AVIATION_NON_COMPLIANCE_SUBMIT_EXECUTE_TASK = "PERM_AVIATION_NON_COMPLIANCE_SUBMIT_EXECUTE_TASK";

    public static final String PERM_AVIATION_NON_COMPLIANCE_PEER_REVIEW_VIEW_TASK = "PERM_AVIATION_NON_COMPLIANCE_PEER_REVIEW_VIEW_TASK";
    public static final String PERM_AVIATION_NON_COMPLIANCE_PEER_REVIEW_EXECUTE_TASK = "PERM_AVIATION_NON_COMPLIANCE_PEER_REVIEW_EXECUTE_TASK";

    // Aviation Account Closure
    public static final String PERM_AVIATION_ACCOUNT_CLOSURE_SUBMIT_VIEW_TASK = "PERM_AVIATION_ACCOUNT_CLOSURE_SUBMIT_VIEW_TASK";
    public static final String PERM_AVIATION_ACCOUNT_CLOSURE_SUBMIT_EXECUTE_TASK = "PERM_AVIATION_ACCOUNT_CLOSURE_SUBMIT_EXECUTE_TASK";
    
}
