/**
 * PMRV API Documentation
 * PMRV API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface ActivitiesDescription {
  operatorType: 'COMMERCIAL' | 'NON_COMMERCIAL';
  flightTypes: Array<'SCHEDULED' | 'NON_SCHEDULED'>;
  operationScopes: Array<'UK_DOMESTIC' | 'UK_TO_EEA_COUNTRIES'>;
  activityDescription: string;
}
