/**
 * PMRV API Documentation
 * PMRV API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Aer } from './aer';
import { InstallationOperatorDetails } from './installationOperatorDetails';
import { MonitoringPlanVersion } from './monitoringPlanVersion';
import { PermitOriginatedData } from './permitOriginatedData';
import { RequestActionPayload } from './requestActionPayload';

export interface AerApplicationAmendsSubmittedRequestActionPayload extends RequestActionPayload {
  aer: Aer;
  reportingYear: number;
  installationOperatorDetails: InstallationOperatorDetails;
  permitOriginatedData?: PermitOriginatedData;
  monitoringPlanVersions?: Array<MonitoringPlanVersion>;
  aerAttachments?: { [key: string]: string };
}
