/**
 * METS API Documentation
 * METS API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AerReviewDecision } from './aerReviewDecision';
import { ReviewDecisionDetails } from './reviewDecisionDetails';

export interface AerDataReviewDecision extends AerReviewDecision {
  type: 'ACCEPTED' | 'OPERATOR_AMENDS_NEEDED';
  details?: ReviewDecisionDetails;
}
