/**
 * METS API Documentation
 * METS API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AerInitiatorRequest } from './aerInitiatorRequest';
import { RequestMetadata } from './requestMetadata';

export interface AerRequestMetadata extends RequestMetadata {
  year: number;
  emissions: string;
  overallAssessmentType?: 'VERIFIED_AS_SATISFACTORY' | 'VERIFIED_WITH_COMMENTS' | 'NOT_VERIFIED';
  initiatorRequest: AerInitiatorRequest;
}
