/**
 * PMRV API Documentation
 * PMRV API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AerReviewDecision } from './aerReviewDecision';

export interface AerSaveReviewGroupDecisionRequestTaskActionPayloadAllOf {
  group?:
    | 'INSTALLATION_DETAILS'
    | 'FUELS_AND_EQUIPMENT'
    | 'ADDITIONAL_INFORMATION'
    | 'EMISSIONS_SUMMARY'
    | 'CALCULATION_CO2'
    | 'MEASUREMENT_CO2'
    | 'FALLBACK'
    | 'MEASUREMENT_N2O'
    | 'CALCULATION_PFC'
    | 'INHERENT_CO2'
    | 'VERIFIER_DETAILS'
    | 'OPINION_STATEMENT'
    | 'ETS_COMPLIANCE_RULES'
    | 'COMPLIANCE_MONITORING_REPORTING'
    | 'OVERALL_DECISION'
    | 'UNCORRECTED_MISSTATEMENTS'
    | 'UNCORRECTED_NON_CONFORMITIES'
    | 'UNCORRECTED_NON_COMPLIANCES'
    | 'RECOMMENDED_IMPROVEMENTS'
    | 'CLOSE_DATA_GAPS_METHODOLOGIES'
    | 'MATERIALITY_LEVEL'
    | 'SUMMARY_OF_CONDITIONS'
    | 'ACTIVITY_LEVEL_REPORT'
    | 'VERIFICATION_ACTIVITY_LEVEL_REPORT';
  decision?: AerReviewDecision;
  reviewSectionsCompleted?: { [key: string]: boolean };
}
