/**
 * PMRV API Documentation
 * PMRV API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ActivityLevelReport } from './activityLevelReport';
import { ComplianceMonitoringReporting } from './complianceMonitoringReporting';
import { EtsComplianceRules } from './etsComplianceRules';
import { MaterialityLevel } from './materialityLevel';
import { MethodologiesToCloseDataGaps } from './methodologiesToCloseDataGaps';
import { OpinionStatement } from './opinionStatement';
import { OverallAssessment } from './overallAssessment';
import { RecommendedImprovements } from './recommendedImprovements';
import { SummaryOfConditions } from './summaryOfConditions';
import { UncorrectedMisstatements } from './uncorrectedMisstatements';
import { UncorrectedNonCompliances } from './uncorrectedNonCompliances';
import { UncorrectedNonConformities } from './uncorrectedNonConformities';
import { VerificationTeamDetails } from './verificationTeamDetails';
import { VerifierContact } from './verifierContact';

export interface AerSaveApplicationVerificationRequestTaskActionPayloadAllOf {
  verificationTeamDetails?: VerificationTeamDetails;
  verifierContact?: VerifierContact;
  materialityLevel?: MaterialityLevel;
  complianceMonitoringReporting?: ComplianceMonitoringReporting;
  etsComplianceRules?: EtsComplianceRules;
  summaryOfConditions?: SummaryOfConditions;
  overallAssessment?: OverallAssessment;
  methodologiesToCloseDataGaps?: MethodologiesToCloseDataGaps;
  opinionStatement?: OpinionStatement;
  uncorrectedMisstatements?: UncorrectedMisstatements;
  recommendedImprovements?: RecommendedImprovements;
  uncorrectedNonConformities?: UncorrectedNonConformities;
  uncorrectedNonCompliances?: UncorrectedNonCompliances;
  activityLevelReport?: ActivityLevelReport;
  verificationSectionsCompleted?: { [key: string]: Array<boolean> };
}
