/**
 * PMRV API Documentation
 * PMRV API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AirImprovement } from './airImprovement';
import { OperatorAirImprovementResponse } from './operatorAirImprovementResponse';

export interface AirApplicationSubmittedRequestActionPayloadAllOf {
  airImprovements?: { [key: string]: AirImprovement };
  reportingYear?: number;
  operatorImprovementResponses?: { [key: string]: OperatorAirImprovementResponse };
  airAttachments?: { [key: string]: string };
  airSectionsCompleted?: { [key: string]: boolean };
}
