/**
 * METS API Documentation
 * METS API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ALR } from './aLR';
import { ALRVerificationReport } from './aLRVerificationReport';
import { InstallationOperatorDetails } from './installationOperatorDetails';

export interface ALRApplicationSubmittedRequestActionPayloadAllOf {
  alr?: ALR;
  installationOperatorDetails?: InstallationOperatorDetails;
  verificationPerformed?: boolean;
  verificationReport?: ALRVerificationReport;
  alrAttachments?: { [key: string]: string };
  verificationAttachments?: { [key: string]: string };
}
