/**
 * METS API Documentation
 * METS API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ALR } from './aLR';
import { RequestTaskPayload } from './requestTaskPayload';

export interface ALRApplicationSubmitRequestTaskPayload extends RequestTaskPayload {
  alr?: ALR;
  verificationSectionsCompleted?: { [key: string]: Array<boolean> };
  alrSectionsCompleted?: { [key: string]: boolean };
  alrAttachments?: { [key: string]: string };
  verificationPerformed?: boolean;
  verificationBodyId?: number;
}
