/**
 * METS API Documentation
 * METS API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ALR } from './aLR';
import { ALRAlrDataRegulatorReviewDecision } from './aLRAlrDataRegulatorReviewDecision';
import { ALRApplicationRegulatorReviewOutcome } from './aLRApplicationRegulatorReviewOutcome';
import { ALRReviewDecision } from './aLRReviewDecision';
import { ALRVerificationReport } from './aLRVerificationReport';
import { ALRVerificationReportDataRegulatorReviewDecision } from './aLRVerificationReportDataRegulatorReviewDecision';

export interface ALRApplicationRegulatorReviewSubmitRequestTaskPayloadAllOf {
  alr?: ALR;
  verificationSectionsCompleted?: { [key: string]: Array<boolean> };
  alrSectionsCompleted?: { [key: string]: boolean };
  alrAttachments?: { [key: string]: string };
  alrFileVersion?: number;
  verificationReport?: ALRVerificationReport;
  verificationAttachments?: { [key: string]: string };
  verifiedAlr?: ALR;
  regulatorReviewOutcome?: ALRApplicationRegulatorReviewOutcome;
  regulatorReviewSectionsCompleted?: { [key: string]: boolean };
  regulatorReviewGroupDecisions?: {
    [key: string]:
      | ALRReviewDecision
      | ALRAlrDataRegulatorReviewDecision
      | ALRVerificationReportDataRegulatorReviewDecision;
  };
  regulatorReviewAttachments?: { [key: string]: string };
}
