/**
 * METS API Documentation
 * METS API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ALRAlrDataRegulatorReviewRequiredChange } from './aLRAlrDataRegulatorReviewRequiredChange';
import { ALRRegulatorReviewDecisionDetails } from './aLRRegulatorReviewDecisionDetails';

export interface ALRAlrDataRegulatorReviewOperatorAmendsNeededDecisionDetails
  extends ALRRegulatorReviewDecisionDetails {
  verificationRequired?: boolean;
  requiredChanges: Array<ALRAlrDataRegulatorReviewRequiredChange>;
}
