/**
 * METS API Documentation
 * METS API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ALR } from './aLR';
import { ALRAlrDataRegulatorReviewDecision } from './aLRAlrDataRegulatorReviewDecision';
import { ALRReviewDecision } from './aLRReviewDecision';
import { ALRVerificationReportDataRegulatorReviewDecision } from './aLRVerificationReportDataRegulatorReviewDecision';
import { RequestTaskPayload } from './requestTaskPayload';

export interface ALRApplicationAmendsSubmitRequestTaskPayload extends RequestTaskPayload {
  alr?: ALR;
  verificationSectionsCompleted?: { [key: string]: Array<boolean> };
  alrSectionsCompleted?: { [key: string]: boolean };
  alrAttachments?: { [key: string]: string };
  alrFileVersion?: number;
  verificationPerformed?: boolean;
  verificationBodyId?: number;
  regulatorReviewSectionsCompleted?: { [key: string]: boolean };
  regulatorReviewGroupDecisions?: {
    [key: string]:
      | ALRReviewDecision
      | ALRAlrDataRegulatorReviewDecision
      | ALRVerificationReportDataRegulatorReviewDecision;
  };
  regulatorReviewAttachments?: { [key: string]: string };
}
