/**
 * METS API Documentation
 * METS API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ALR } from './aLR';
import { ALRGrantAuthorityResponse } from './aLRGrantAuthorityResponse';
import { ALRGrantAuthorityWithCorrectionsResponse } from './aLRGrantAuthorityWithCorrectionsResponse';
import { ALRRejectAuthorityResponse } from './aLRRejectAuthorityResponse';

export interface ALRApplicationAuthorityReviewOutcome {
  alr: ALR;
  submissionDate?: string;
  authorityResponse: ALRGrantAuthorityResponse | ALRGrantAuthorityWithCorrectionsResponse | ALRRejectAuthorityResponse;
}
