/**
 * METS API Documentation
 * METS API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ALRAlrDataRegulatorReviewDecision } from './aLRAlrDataRegulatorReviewDecision';
import { ALRReviewDecision } from './aLRReviewDecision';
import { ALRVerificationReportDataRegulatorReviewDecision } from './aLRVerificationReportDataRegulatorReviewDecision';

export interface ALRSaveRegulatorReviewGroupDecisionRequestTaskActionPayloadAllOf {
  group?: 'ALR' | 'OPINION_STATEMENT' | 'OVERALL_DECISION';
  decision?: ALRReviewDecision | ALRAlrDataRegulatorReviewDecision | ALRVerificationReportDataRegulatorReviewDecision;
  regulatorReviewSectionsCompleted?: { [key: string]: boolean };
}
