/**
 * METS API Documentation
 * METS API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ALRNotVerifiedOverallVerificationAssessment } from './aLRNotVerifiedOverallVerificationAssessment';
import { ALRVerificationOpinionStatement } from './aLRVerificationOpinionStatement';
import { ALRVerifiedSatisfactoryOverallVerificationAssessment } from './aLRVerifiedSatisfactoryOverallVerificationAssessment';
import { ALRVerifiedWithCommentsOverallVerificationAssessment } from './aLRVerifiedWithCommentsOverallVerificationAssessment';
import { VerificationBodyDetails } from './verificationBodyDetails';

export interface ALRVerificationReport {
  verificationBodyId?: number;
  verificationBodyDetails?: VerificationBodyDetails;
  opinionStatement: ALRVerificationOpinionStatement;
  overallAssessment:
    | ALRNotVerifiedOverallVerificationAssessment
    | ALRVerifiedSatisfactoryOverallVerificationAssessment
    | ALRVerifiedWithCommentsOverallVerificationAssessment;
}
