/**
 * METS API Documentation
 * METS API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AviationAerCorsia3YearPeriodOffsetting } from './aviationAerCorsia3YearPeriodOffsetting';
import { DecisionNotification } from './decisionNotification';
import { FileInfoDTO } from './fileInfoDTO';
import { RequestActionUserInfo } from './requestActionUserInfo';

export interface AviationAerCorsia3YearPeriodOffsettingApplicationSubmittedRequestActionPayloadAllOf {
  aviationAerCorsia3YearPeriodOffsetting?: AviationAerCorsia3YearPeriodOffsetting;
  decisionNotification?: DecisionNotification;
  usersInfo?: { [key: string]: RequestActionUserInfo };
  officialNotice?: FileInfoDTO;
}
