/**
 * METS API Documentation
 * METS API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AviationAerCorsiaAnnualOffsetting } from './aviationAerCorsiaAnnualOffsetting';
import { RequestTaskActionPayload } from './requestTaskActionPayload';

export interface AviationAerCorsiaAnnualOffsettingSaveRequestTaskActionPayload extends RequestTaskActionPayload {
  aviationAerCorsiaAnnualOffsetting?: AviationAerCorsiaAnnualOffsetting;
  aviationAerCorsiaAnnualOffsettingSectionsCompleted?: { [key: string]: boolean };
}
