/**
 * METS API Documentation
 * METS API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AirOperatingCertificateCorsia } from './airOperatingCertificateCorsia';
import { FlightIdentification } from './flightIdentification';
import { IndividualOrganisation } from './individualOrganisation';
import { LimitedCompanyOrganisation } from './limitedCompanyOrganisation';
import { PartnershipOrganisation } from './partnershipOrganisation';

export interface AviationCorsiaOperatorDetails {
  operatorName: string;
  flightIdentification: FlightIdentification;
  airOperatingCertificate: AirOperatingCertificateCorsia;
  organisationStructure: IndividualOrganisation | LimitedCompanyOrganisation | PartnershipOrganisation;
}
