/**
 * METS API Documentation
 * METS API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface AviationAerCorsiaIndependentReview {
  reviewResults: string;
  name: string;
  position: string;
  email: string;
  line1: string;
  line2?: string;
  city: string;
  country: string;
  postcode?: string;
  state?: string;
}
