/**
 * METS API Documentation
 * METS API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AviationAerCorsia } from './aviationAerCorsia';
import { AviationAerReportingObligationDetails } from './aviationAerReportingObligationDetails';
import { RequestTaskActionPayload } from './requestTaskActionPayload';

export interface AviationAerCorsiaSaveApplicationAmendRequestTaskActionPayload extends RequestTaskActionPayload {
  reportingRequired?: boolean;
  reportingObligationDetails?: AviationAerReportingObligationDetails;
  aer?: AviationAerCorsia;
  aerSectionsCompleted?: { [key: string]: Array<boolean> };
  reviewSectionsCompleted?: { [key: string]: boolean };
}
