/**
 * PMRV API Documentation
 * PMRV API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AerReviewDecision } from './aerReviewDecision';
import { RequestTaskActionPayload } from './requestTaskActionPayload';

export interface AviationAerCorsiaSaveReviewGroupDecisionRequestTaskActionPayload extends RequestTaskActionPayload {
  group:
    | 'SERVICE_CONTACT_DETAILS'
    | 'OPERATOR_DETAILS'
    | 'MONITORING_PLAN_CHANGES'
    | 'MONITORING_APPROACH'
    | 'AGGREGATED_EMISSIONS_DATA'
    | 'AIRCRAFT_DATA'
    | 'EMISSIONS_REDUCTION_CLAIM'
    | 'TOTAL_EMISSIONS'
    | 'ADDITIONAL_DOCUMENTS'
    | 'DATA_GAPS'
    | 'REPORTING_OBLIGATION_DETAILS'
    | 'CONFIDENTIALITY'
    | 'VERIFIER_DETAILS'
    | 'TIME_ALLOCATION_AND_SCOPE'
    | 'VERIFICATION_CRITERIA'
    | 'PROCESS_AND_ANALYSIS_DETAILS'
    | 'MONITORING_APPROACH_EMISSIONS'
    | 'ELIGIBLE_FUELS_REDUCTION_CLAIM'
    | 'UNCORRECTED_MISSTATEMENTS'
    | 'UNCORRECTED_NON_CONFORMITIES'
    | 'UNCORRECTED_NON_COMPLIANCES'
    | 'RECOMMENDED_IMPROVEMENTS'
    | 'CONCLUSIONS_DATA_QUALITY'
    | 'VERIFICATION_STATEMENT_CONCLUSIONS'
    | 'INDEPENDENT_REVIEW';
  decision: AerReviewDecision;
  reviewSectionsCompleted?: { [key: string]: boolean };
}
