/**
 * PMRV API Documentation
 * PMRV API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface AviationAerMaterialityLevel {
  materialityDetails: string;
  accreditationReferenceDocumentTypes: Array<
    | 'UK_ETS_ACCREDITED_VERIFIERS_SI_2020_1265'
    | 'UK_ETS_ACCREDITED_VERIFIERS_EU_2018_2067'
    | 'UK_ETS_ACCREDITED_VERIFIERS_EN_ISO_14065_2020'
    | 'UK_ETS_ACCREDITED_VERIFIERS_EN_ISO_14064_3_2019'
    | 'UK_ETS_ACCREDITED_VERIFIERS_IAF_MD_6_2014'
    | 'UK_ETS_ACCREDITED_VERIFIERS_AUTHORITY_GUIDANCE'
    | 'UK_ETS_ACCREDITED_VERIFIERS_EUROPEAN_COMMISSION_GUIDANCE'
    | 'UK_ETS_ACCREDITED_VERIFIERS_ISAE_3000'
    | 'UK_ETS_ACCREDITED_VERIFIERS_ISAE_3410'
    | 'UK_ETS_RULES_ORDER_2020_1265'
    | 'UK_ETS_RULES_ORDER_2020_1557'
    | 'UK_ETS_RULES_EU_2018_2067'
    | 'UK_ETS_RULES_EU_2018_2066'
    | 'UK_ETS_RULES_EUROPEAN_COMMISSION_GUIDANCE'
    | 'OTHER'
  >;
  otherReference?: string;
}
