/**
 * PMRV API Documentation
 * PMRV API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OperatorImprovementFollowUpResponse } from './operatorImprovementFollowUpResponse';
import { OperatorImprovementResponse } from './operatorImprovementResponse';
import { RegulatorImprovementResponse } from './regulatorImprovementResponse';
import { RequestTaskPayload } from './requestTaskPayload';
import { VirVerificationData } from './virVerificationData';

export interface AviationVirApplicationRespondToRegulatorCommentsRequestTaskPayload extends RequestTaskPayload {
  verificationData?: VirVerificationData;
  operatorImprovementResponses?: { [key: string]: OperatorImprovementResponse };
  virSectionsCompleted?: { [key: string]: boolean };
  virAttachments?: { [key: string]: string };
  regulatorImprovementResponses?: { [key: string]: RegulatorImprovementResponse };
  operatorImprovementFollowUpResponses?: { [key: string]: OperatorImprovementFollowUpResponse };
  virRespondToRegulatorCommentsSectionsCompleted?: { [key: string]: boolean };
}
