/**
 * PMRV API Documentation
 * PMRV API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AviationAerMonitoringPlanVersion } from './aviationAerMonitoringPlanVersion';
import { AviationAerReportingObligationDetails } from './aviationAerReportingObligationDetails';
import { AviationAerUkEts } from './aviationAerUkEts';
import { AviationAerUkEtsVerificationReport } from './aviationAerUkEtsVerificationReport';
import { RequestActionPayload } from './requestActionPayload';
import { ServiceContactDetails } from './serviceContactDetails';

export interface AviationAerUkEtsApplicationVerificationSubmittedRequestActionPayload extends RequestActionPayload {
  reportingRequired?: boolean;
  reportingObligationDetails?: AviationAerReportingObligationDetails;
  aer?: AviationAerUkEts;
  reportingYear?: number;
  serviceContactDetails?: ServiceContactDetails;
  aerMonitoringPlanVersions?: Array<AviationAerMonitoringPlanVersion>;
  aerAttachments?: { [key: string]: string };
  verificationReport?: AviationAerUkEtsVerificationReport;
  totalEmissionsProvided?: string;
  notCoveredChangesProvided?: string;
}
