/**
 * METS API Documentation
 * METS API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AviationAerCorsiaAnnualOffsetting } from './aviationAerCorsiaAnnualOffsetting';
import { PeerReviewDecision } from './peerReviewDecision';
import { RequestActionPayload } from './requestActionPayload';

export interface AviationAerCorsiaAnnualOffsettingPeerReviewDescisionActionPayload extends RequestActionPayload {
  decision: PeerReviewDecision;
  aviationAerCorsiaAnnualOffsetting?: AviationAerCorsiaAnnualOffsetting;
  aviationAerCorsiaAnnualOffsettingSectionsCompleted?: { [key: string]: boolean };
}
