/**
 * PMRV API Documentation
 * PMRV API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AviationAerCorsiaEmissionsReductionClaimVerification } from './aviationAerCorsiaEmissionsReductionClaimVerification';
import { AviationAerCorsiaGeneralInformation } from './aviationAerCorsiaGeneralInformation';
import { AviationAerCorsiaIndependentReview } from './aviationAerCorsiaIndependentReview';
import { AviationAerCorsiaOpinionStatement } from './aviationAerCorsiaOpinionStatement';
import { AviationAerCorsiaProcessAnalysis } from './aviationAerCorsiaProcessAnalysis';
import { AviationAerCorsiaTimeAllocationScope } from './aviationAerCorsiaTimeAllocationScope';
import { AviationAerCorsiaUncorrectedNonConformities } from './aviationAerCorsiaUncorrectedNonConformities';
import { AviationAerCorsiaVerifierDetails } from './aviationAerCorsiaVerifierDetails';
import { AviationAerCorsiaVerifiersConclusions } from './aviationAerCorsiaVerifiersConclusions';
import { AviationAerRecommendedImprovements } from './aviationAerRecommendedImprovements';
import { AviationAerUncorrectedMisstatements } from './aviationAerUncorrectedMisstatements';
import { AviationAerUncorrectedNonCompliances } from './aviationAerUncorrectedNonCompliances';
import { AviationAerVerificationDecision } from './aviationAerVerificationDecision';
import { RequestTaskActionPayload } from './requestTaskActionPayload';

export interface AviationAerCorsiaSaveApplicationVerificationRequestTaskActionPayload extends RequestTaskActionPayload {
  verifierDetails: AviationAerCorsiaVerifierDetails;
  emissionsReductionClaimVerification?: AviationAerCorsiaEmissionsReductionClaimVerification;
  independentReview: AviationAerCorsiaIndependentReview;
  verifiersConclusions: AviationAerCorsiaVerifiersConclusions;
  timeAllocationScope: AviationAerCorsiaTimeAllocationScope;
  processAnalysis: AviationAerCorsiaProcessAnalysis;
  generalInformation: AviationAerCorsiaGeneralInformation;
  overallDecision: AviationAerVerificationDecision;
  opinionStatement: AviationAerCorsiaOpinionStatement;
  uncorrectedMisstatements: AviationAerUncorrectedMisstatements;
  recommendedImprovements: AviationAerRecommendedImprovements;
  uncorrectedNonConformities: AviationAerCorsiaUncorrectedNonConformities;
  uncorrectedNonCompliances: AviationAerUncorrectedNonCompliances;
  verificationSectionsCompleted?: { [key: string]: Array<boolean> };
}
