/**
 * METS API Documentation
 * METS API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AviationAerCorsia3YearPeriodOffsetting } from './aviationAerCorsia3YearPeriodOffsetting';
import { DecisionNotification } from './decisionNotification';
import { RequestTaskPayload } from './requestTaskPayload';

export interface AviationAerCorsia3YearPeriodOffsettingApplicationSubmitRequestTaskPayload extends RequestTaskPayload {
  aviationAerCorsia3YearPeriodOffsetting?: AviationAerCorsia3YearPeriodOffsetting;
  aviationAerCorsia3YearPeriodOffsettingSectionsCompleted?: { [key: string]: boolean };
  decisionNotification?: DecisionNotification;
}
