/**
 * PMRV API Documentation
 * PMRV API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OperatorImprovementResponse } from './operatorImprovementResponse';
import { RegulatorReviewResponse } from './regulatorReviewResponse';
import { VirVerificationData } from './virVerificationData';

export interface AviationVirApplicationReviewRequestTaskPayloadAllOf {
  verificationData?: VirVerificationData;
  operatorImprovementResponses?: { [key: string]: OperatorImprovementResponse };
  virSectionsCompleted?: { [key: string]: boolean };
  virAttachments?: { [key: string]: string };
  regulatorReviewResponse?: RegulatorReviewResponse;
  reviewSectionsCompleted?: { [key: string]: boolean };
  rfiAttachments?: { [key: string]: string };
}
