/**
 * METS API Documentation
 * METS API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LegalEntityDTO } from './legalEntityDTO';
import { LocationDTO } from './locationDTO';
import { LocationOffShoreDTO } from './locationOffShoreDTO';
import { LocationOnShoreDTO } from './locationOnShoreDTO';
import { LocationOnShoreStateDTO } from './locationOnShoreStateDTO';

export interface AviationAccountDTO {
  id?: number;
  accountType: 'INSTALLATION' | 'AVIATION';
  name: string;
  emissionTradingScheme: 'UK_ETS_INSTALLATIONS' | 'EU_ETS_INSTALLATIONS' | 'UK_ETS_AVIATION' | 'CORSIA';
  competentAuthority: 'ENGLAND' | 'NORTHERN_IRELAND' | 'OPRED' | 'SCOTLAND' | 'WALES';
  commencementDate: string;
  legalEntity?: LegalEntityDTO;
  location?: LocationDTO | LocationOffShoreDTO | LocationOnShoreDTO | LocationOnShoreStateDTO;
  acceptedDate?: string;
  sopId?: number;
  registryId?: number;
  status?: 'NEW' | 'LIVE' | 'CLOSED';
  crcoCode?: string;
  reportingStatus?: 'REQUIRED_TO_REPORT' | 'EXEMPT_COMMERCIAL' | 'EXEMPT_NON_COMMERCIAL';
  reportingStatusReason?: string;
  closureReason?: string;
  closedByName?: string;
  closingDate?: string;
}
