/**
 * METS API Documentation
 * METS API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AviationAerCorsiaAnnualOffsetting } from './aviationAerCorsiaAnnualOffsetting';
import { DecisionNotification } from './decisionNotification';
import { RequestTaskPayload } from './requestTaskPayload';

export interface AviationAerCorsiaAnnualOffsettingApplicationSubmitRequestTaskPayload extends RequestTaskPayload {
  aviationAerCorsiaAnnualOffsetting?: AviationAerCorsiaAnnualOffsetting;
  aviationAerCorsiaAnnualOffsettingSectionsCompleted?: { [key: string]: boolean };
  decisionNotification?: DecisionNotification;
}
