/**
 * PMRV API Documentation
 * PMRV API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AerReviewDecision } from './aerReviewDecision';

export interface AviationAerUkEtsSaveReviewGroupDecisionRequestTaskActionPayloadAllOf {
  group?:
    | 'SERVICE_CONTACT_DETAILS'
    | 'OPERATOR_DETAILS'
    | 'MONITORING_PLAN_CHANGES'
    | 'MONITORING_APPROACH'
    | 'AGGREGATED_EMISSIONS_DATA'
    | 'AIRCRAFT_DATA'
    | 'EMISSIONS_REDUCTION_CLAIM'
    | 'TOTAL_EMISSIONS'
    | 'ADDITIONAL_DOCUMENTS'
    | 'DATA_GAPS'
    | 'REPORTING_OBLIGATION_DETAILS'
    | 'VERIFIER_DETAILS'
    | 'OPINION_STATEMENT'
    | 'ETS_COMPLIANCE_RULES'
    | 'COMPLIANCE_MONITORING_REPORTING'
    | 'OVERALL_DECISION'
    | 'UNCORRECTED_MISSTATEMENTS'
    | 'UNCORRECTED_NON_CONFORMITIES'
    | 'UNCORRECTED_NON_COMPLIANCES'
    | 'RECOMMENDED_IMPROVEMENTS'
    | 'CLOSE_DATA_GAPS_METHODOLOGIES'
    | 'MATERIALITY_LEVEL'
    | 'EMISSIONS_REDUCTION_CLAIM_VERIFICATION';
  decision?: AerReviewDecision;
  reviewSectionsCompleted?: { [key: string]: boolean };
}
