/**
 * METS API Documentation
 * METS API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BDR } from './bDR';
import { BDRBdrDataRegulatorReviewDecision } from './bDRBdrDataRegulatorReviewDecision';
import { BDRReviewDecision } from './bDRReviewDecision';
import { BDRVerificationReportDataRegulatorReviewDecision } from './bDRVerificationReportDataRegulatorReviewDecision';
import { RequestTaskPayload } from './requestTaskPayload';

export interface BDRApplicationAmendsSubmitRequestTaskPayload extends RequestTaskPayload {
  bdr?: BDR;
  verificationSectionsCompleted?: { [key: string]: Array<boolean> };
  bdrSectionsCompleted?: { [key: string]: boolean };
  bdrAttachments?: { [key: string]: string };
  verificationPerformed?: boolean;
  verificationBodyId?: number;
  regulatorReviewSectionsCompleted?: { [key: string]: boolean };
  regulatorReviewGroupDecisions?: {
    [key: string]:
      | BDRReviewDecision
      | BDRBdrDataRegulatorReviewDecision
      | BDRVerificationReportDataRegulatorReviewDecision;
  };
  regulatorReviewAttachments?: { [key: string]: string };
}
