/**
 * METS API Documentation
 * METS API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BDR } from './bDR';

export interface BDRApplicationSubmitRequestTaskPayloadAllOf {
  bdr?: BDR;
  verificationSectionsCompleted?: { [key: string]: Array<boolean> };
  bdrSectionsCompleted?: { [key: string]: boolean };
  bdrAttachments?: { [key: string]: string };
  verificationPerformed?: boolean;
  verificationBodyId?: number;
}
