/**
 * METS API Documentation
 * METS API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BDR } from './bDR';
import { BDRVerificationReport } from './bDRVerificationReport';
import { InstallationOperatorDetails } from './installationOperatorDetails';
import { RequestActionPayload } from './requestActionPayload';

export interface BDRApplicationSubmittedRequestActionPayload extends RequestActionPayload {
  bdr: BDR;
  installationOperatorDetails: InstallationOperatorDetails;
  verificationPerformed?: boolean;
  verificationReport?: BDRVerificationReport;
  bdrAttachments?: { [key: string]: string };
  verificationAttachments?: { [key: string]: string };
}
