/**
 * METS API Documentation
 * METS API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BDRS2Files } from './bDRS2Files';
import { BDRS2GuardQuestions } from './bDRS2GuardQuestions';

export interface BDRS2 {
  bdrs2guardQuestions: BDRS2GuardQuestions;
  bdrs2Files?: BDRS2Files;
  mmpFiles?: BDRS2Files;
}
