/**
 * METS API Documentation
 * METS API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BDRS2Bdrs2DataRegulatorReviewDecision } from './bDRS2Bdrs2DataRegulatorReviewDecision';
import { BDRS2ReviewDecision } from './bDRS2ReviewDecision';
import { BDRS2VerificationReportDataRegulatorReviewDecision } from './bDRS2VerificationReportDataRegulatorReviewDecision';
import { RequestActionPayload } from './requestActionPayload';

export interface BDRS2RegulatorReviewReturnedForAmendsRequestActionPayload extends RequestActionPayload {
  regulatorReviewGroupDecisions: {
    [key: string]:
      | BDRS2ReviewDecision
      | BDRS2Bdrs2DataRegulatorReviewDecision
      | BDRS2VerificationReportDataRegulatorReviewDecision;
  };
  regulatorReviewAttachments?: { [key: string]: string };
}
