/**
 * METS API Documentation
 * METS API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BDRS2 } from './bDRS2';
import { BDRS2VerificationReport } from './bDRS2VerificationReport';
import { RequestTaskPayload } from './requestTaskPayload';

export interface BDRS2ApplicationVerificationSubmitRequestTaskPayload extends RequestTaskPayload {
  bdrs2?: BDRS2;
  verificationSectionsCompleted?: { [key: string]: Array<boolean> };
  regulatorReviewSectionsCompleted?: { [key: string]: boolean };
  bdrs2SectionsCompleted?: { [key: string]: boolean };
  bdrs2Attachments?: { [key: string]: string };
  bdrs2FileVersion?: number;
  verificationReport?: BDRS2VerificationReport;
  verificationAttachments?: { [key: string]: string };
}
