/**
 * METS API Documentation
 * METS API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface BDRS2GuardQuestions {
  continueApplicationForFreeAllocationType: 'CONTINUE_AS_MAIN_SCHEME_PARTICIPANT' | 'CONTINUE_AS_HSE' | 'WITHDRAW';
  applicationWithdrawalReason?: string;
  covidAdjustments: boolean;
  inEiteSector: boolean;
  requiresAdditionalSubInstallationSplitsForCbam?: boolean;
}
