/**
 * METS API Documentation
 * METS API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BDRS2 } from './bDRS2';
import { BDRS2VerificationReport } from './bDRS2VerificationReport';
import { InstallationOperatorDetails } from './installationOperatorDetails';

export interface BDRS2ApplicationAmendsSubmittedRequestActionPayloadAllOf {
  bdrs2?: BDRS2;
  installationOperatorDetails?: InstallationOperatorDetails;
  verificationPerformed?: boolean;
  verificationReport?: BDRS2VerificationReport;
  bdrs2Attachments?: { [key: string]: string };
  verificationAttachments?: { [key: string]: string };
}
