/**
 * METS API Documentation
 * METS API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BDRS2 } from './bDRS2';

export interface BDRS2ApplicationSubmitRequestTaskPayloadAllOf {
  bdrs2?: BDRS2;
  bdrs2SectionsCompleted?: { [key: string]: boolean };
  bdrs2Attachments?: { [key: string]: string };
  bdrs2FileVersion?: number;
}
