/**
 * METS API Documentation
 * METS API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BDRS2 } from './bDRS2';
import { BDRS2ApplicationRegulatorReviewOutcome } from './bDRS2ApplicationRegulatorReviewOutcome';
import { BDRS2Bdrs2DataRegulatorReviewDecision } from './bDRS2Bdrs2DataRegulatorReviewDecision';
import { BDRS2ReviewDecision } from './bDRS2ReviewDecision';
import { BDRS2VerificationReport } from './bDRS2VerificationReport';
import { BDRS2VerificationReportDataRegulatorReviewDecision } from './bDRS2VerificationReportDataRegulatorReviewDecision';
import { InstallationOperatorDetails } from './installationOperatorDetails';

export interface BDRS2ApplicationCompletedRequestActionPayloadAllOf {
  bdrs2?: BDRS2;
  installationOperatorDetails?: InstallationOperatorDetails;
  verificationPerformed?: boolean;
  verificationReport?: BDRS2VerificationReport;
  bdrs2Attachments?: { [key: string]: string };
  verificationAttachments?: { [key: string]: string };
  verifiedBdrs2?: BDRS2;
  regulatorReviewOutcome?: BDRS2ApplicationRegulatorReviewOutcome;
  regulatorReviewGroupDecisions?: {
    [key: string]:
      | BDRS2ReviewDecision
      | BDRS2Bdrs2DataRegulatorReviewDecision
      | BDRS2VerificationReportDataRegulatorReviewDecision;
  };
  regulatorReviewAttachments?: { [key: string]: string };
}
