/**
 * METS API Documentation
 * METS API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BDRS2RegulatorReviewNotes } from './bDRS2RegulatorReviewNotes';

export interface BDRS2ApplicationRegulatorReviewOutcome {
  freeAllocationOpinion?: 'SENT_TO_AUTHORITY' | 'WITHDRAWN';
  freeAllocationReviewNotes?: BDRS2RegulatorReviewNotes;
  covidAdjustmentsOpinion?: 'SENT_TO_AUTHORITY' | 'NO_ADJUSTMENTS';
  covidAdjustmentsReviewNotes?: BDRS2RegulatorReviewNotes;
  installationSectorOpinion?: 'IN_SCOPE_OF_CBAM' | 'CBAM_DOES_NOT_APPLY';
  installationSectorReviewNotes?: BDRS2RegulatorReviewNotes;
  cbamSplitOpinion?: 'SENT_TO_AUTHORITY' | 'NO_SPLIT_APPLICABLE';
  cbamSplitReviewNotes?: BDRS2RegulatorReviewNotes;
  file?: string;
  supportingFiles?: Array<string>;
}
