/**
 * METS API Documentation
 * METS API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BDRS2NotVerifiedOverallVerificationAssessment } from './bDRS2NotVerifiedOverallVerificationAssessment';
import { BDRS2VerificationOpinionStatement } from './bDRS2VerificationOpinionStatement';
import { BDRS2VerifiedSatisfactoryOverallVerificationAssessment } from './bDRS2VerifiedSatisfactoryOverallVerificationAssessment';
import { BDRS2VerifiedWithCommentsOverallVerificationAssessment } from './bDRS2VerifiedWithCommentsOverallVerificationAssessment';

export interface BDRS2ApplicationVerificationSaveRequestTaskActionPayloadAllOf {
  opinionStatement?: BDRS2VerificationOpinionStatement;
  overallAssessment?:
    | BDRS2NotVerifiedOverallVerificationAssessment
    | BDRS2VerifiedSatisfactoryOverallVerificationAssessment
    | BDRS2VerifiedWithCommentsOverallVerificationAssessment;
  verificationSectionsCompleted?: { [key: string]: Array<boolean> };
}
