/**
 * METS API Documentation
 * METS API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CalculationAnalysisMethod } from './calculationAnalysisMethod';
import { CalculationConversionFactorStandardReferenceSource } from './calculationConversionFactorStandardReferenceSource';
import { NoHighestRequiredTierJustification } from './noHighestRequiredTierJustification';

export interface CalculationConversionFactor {
  exist?: boolean;
  tier?: 'TIER_2' | 'TIER_1' | 'NO_TIER';
  isHighestRequiredTier?: boolean;
  noHighestRequiredTierJustification?: NoHighestRequiredTierJustification;
  defaultValueApplied?: boolean;
  standardReferenceSource?: CalculationConversionFactorStandardReferenceSource;
  analysisMethodUsed?: boolean;
  analysisMethods?: Array<CalculationAnalysisMethod>;
}
