/**
 * METS API Documentation
 * METS API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ManuallyProvidedEmissions } from './manuallyProvidedEmissions';

export interface CalculationManualEmissionCalculationParamValues {
  netCalorificValue?: string;
  ncvMeasurementUnit?: 'GJ_PER_TONNE' | 'GJ_PER_NM3';
  emissionFactor?: string;
  efMeasurementUnit?: 'TONNES_OF_CO2_PER_TJ' | 'TONNES_OF_CO2_PER_NM3' | 'TONNES_OF_CO2_PER_TONNE';
  oxidationFactor?: string;
  totalReportableEmissions: string;
  totalSustainableBiomassEmissions?: string;
  calculationCorrect: boolean;
  providedEmissions?: ManuallyProvidedEmissions;
  carbonContent?: string;
  carbonContentMeasurementUnit?:
    | 'TONNES_OF_CO2_PER_NM3'
    | 'TONNES_OF_CO2_PER_TONNE'
    | 'TONNES_OF_CARBON_PER_NM3'
    | 'TONNES_OF_CARBON_PER_TONNE';
  conversionFactor?: string;
}
