/**
 * METS API Documentation
 * METS API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CalculationSourceStreamCategoryAppliedTier } from './calculationSourceStreamCategoryAppliedTier';
import { SamplingPlan } from './samplingPlan';

export interface CalculationOfCO2MonitoringApproachAllOf {
  hasTransfer?: boolean;
  approachDescription?: string;
  samplingPlan?: SamplingPlan;
  sourceStreamCategoryAppliedTiers?: Array<CalculationSourceStreamCategoryAppliedTier>;
}
