/**
 * PMRV API Documentation
 * PMRV API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface CalculationNetCalorificValueMonitoringTierAllOf {
  tier?: 'NO_TIER' | 'TIER_1' | 'TIER_2A' | 'TIER_2B' | 'TIER_3';
}
