/**
 * METS API Documentation
 * METS API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CalculationActivityDataAggregationMeteringCalcMethod } from './calculationActivityDataAggregationMeteringCalcMethod';
import { CalculationActivityDataContinuousMeteringCalcMethod } from './calculationActivityDataContinuousMeteringCalcMethod';
import { CalculationEmissionCalculationParamValues } from './calculationEmissionCalculationParamValues';

export interface CalculationParameterCalculationMethod {
  type: 'REGIONAL_DATA' | 'NATIONAL_INVENTORY_DATA' | 'MANUAL';
  calculationActivityDataCalculationMethod:
    | CalculationActivityDataAggregationMeteringCalcMethod
    | CalculationActivityDataContinuousMeteringCalcMethod;
  emissionCalculationParamValues?: CalculationEmissionCalculationParamValues;
}
