/**
 * METS API Documentation
 * METS API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AerMonitoringApproachEmissions } from './aerMonitoringApproachEmissions';
import { CalculationSourceStreamEmission } from './calculationSourceStreamEmission';

export interface CalculationOfCO2Emissions extends AerMonitoringApproachEmissions {
  hasTransfer?: boolean;
  sourceStreamEmissions: Array<CalculationSourceStreamEmission>;
}
