/**
 * METS API Documentation
 * METS API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface Connection {
  connectionNo: string;
  installationOrEntityName: string;
  entityType: 'ETS_INSTALLATION' | 'NON_ETS_INSTALLATION' | 'NITRIC_ACID_PRODUCTION' | 'HEAT_DISTRIBUTION_NETWORK';
  connectionType:
    | 'MEASURABLE_HEAT'
    | 'WASTE_GAS'
    | 'TRANSFERRED_CO2_FOR_USE'
    | 'TRANSFERRED_CO2_FOR_STORAGE'
    | 'INTERMEDIATE_PRODUCTS';
  flowDirection: 'IMPORT' | 'EXPORT';
  installationId?: string;
  contactPersonName: string;
  emailAddress: string;
  phoneNumber: string;
}
