/**
 * METS API Documentation
 * METS API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface CountyAddressDTO {
  line1?: string;
  address_line_1?: string;
  line2?: string;
  address_line_2?: string;
  country?: string;
  city?: string;
  locality?: string;
  postal_code?: string;
  postcode?: string;
}
