/**
 * PMRV API Documentation
 * PMRV API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DoalAuthority } from './doalAuthority';
import { PreliminaryAllocation } from './preliminaryAllocation';
import { RequestTaskPayload } from './requestTaskPayload';

export interface DoalAuthorityResponseRequestTaskPayload extends RequestTaskPayload {
  regulatorPreliminaryAllocations?: Array<PreliminaryAllocation>;
  doalAuthority: DoalAuthority;
  doalSectionsCompleted?: { [key: string]: boolean };
  doalAttachments?: { [key: string]: string };
}
