/**
 * PMRV API Documentation
 * PMRV API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DoalDetermination } from './doalDetermination';
import { WithholdingAllowancesNotice } from './withholdingAllowancesNotice';

export interface DoalProceedToAuthorityDetermination extends DoalDetermination {
  articleReasonGroupType: 'ARTICLE_6A_REASONS' | 'ARTICLE_34H_REASONS';
  articleReasonItems: Array<
    | 'ALLOCATION_ADJUSTMENT_UNDER_ARTICLE_5'
    | 'SETTING_ALLOCATION_UNDER_ARTICLE_3A'
    | 'SETTING_HAL_AND_ALLOCATION_UNDER_ARTICLE_3A'
    | 'ADJUSTMENT_OF_PARAMETERS_OTHER_THAN_ACTIVITY_LEVEL'
    | 'ERROR_IN_BASELINE_DATA_REPORT'
    | 'ERROR_IN_NEW_ENTRANT_DATA_REPORT'
    | 'ERROR_IN_ACTIVITY_LEVEL_REPORT'
    | 'ERROR_MADE_BY_REGULATOR_OR_AUTHORITY'
  >;
  hasWithholdingOfAllowances: boolean;
  withholdingAllowancesNotice?: WithholdingAllowancesNotice;
  needsOfficialNotice: boolean;
}
