/**
 * PMRV API Documentation
 * PMRV API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EmpAbbreviations } from './empAbbreviations';
import { EmpAdditionalDocuments } from './empAdditionalDocuments';
import { EmpApplicationTimeframeInfo } from './empApplicationTimeframeInfo';
import { EmpBlockHourMethodProcedures } from './empBlockHourMethodProcedures';
import { EmpBlockOnBlockOffMethodProcedures } from './empBlockOnBlockOffMethodProcedures';
import { EmpDataGaps } from './empDataGaps';
import { EmpEmissionsMonitoringApproach } from './empEmissionsMonitoringApproach';
import { EmpEmissionSources } from './empEmissionSources';
import { EmpEmissionsReductionClaim } from './empEmissionsReductionClaim';
import { EmpFlightAndAircraftProcedures } from './empFlightAndAircraftProcedures';
import { EmpFuelUpliftMethodProcedures } from './empFuelUpliftMethodProcedures';
import { EmpManagementProcedures } from './empManagementProcedures';
import { EmpMethodAProcedures } from './empMethodAProcedures';
import { EmpMethodBProcedures } from './empMethodBProcedures';
import { EmpOperatorDetails } from './empOperatorDetails';

export interface EmissionsMonitoringPlanUkEts {
  abbreviations: EmpAbbreviations;
  additionalDocuments: EmpAdditionalDocuments;
  applicationTimeframeInfo: EmpApplicationTimeframeInfo;
  flightAndAircraftProcedures: EmpFlightAndAircraftProcedures;
  emissionSources: EmpEmissionSources;
  emissionsReductionClaim: EmpEmissionsReductionClaim;
  emissionsMonitoringApproach: EmpEmissionsMonitoringApproach;
  managementProcedures: EmpManagementProcedures;
  operatorDetails: EmpOperatorDetails;
  methodAProcedures?: EmpMethodAProcedures;
  methodBProcedures?: EmpMethodBProcedures;
  blockOnBlockOffMethodProcedures?: EmpBlockOnBlockOffMethodProcedures;
  fuelUpliftMethodProcedures?: EmpFuelUpliftMethodProcedures;
  dataGaps?: EmpDataGaps;
  blockHourMethodProcedures?: EmpBlockHourMethodProcedures;
}
