/**
 * PMRV API Documentation
 * PMRV API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EmissionsMonitoringPlanCorsia } from './emissionsMonitoringPlanCorsia';
import { RequestActionPayload } from './requestActionPayload';
import { ServiceContactDetails } from './serviceContactDetails';

export interface EmpIssuanceCorsiaApplicationSubmittedRequestActionPayload extends RequestActionPayload {
  emissionsMonitoringPlan: EmissionsMonitoringPlanCorsia;
  serviceContactDetails: ServiceContactDetails;
  empSectionsCompleted?: { [key: string]: Array<boolean> };
  empAttachments?: { [key: string]: string };
}
