/**
 * PMRV API Documentation
 * PMRV API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EmissionsMonitoringPlanUkEts } from './emissionsMonitoringPlanUkEts';
import { EmpIssuanceDetermination } from './empIssuanceDetermination';
import { EmpIssuanceReviewDecision } from './empIssuanceReviewDecision';
import { RequestTaskPayload } from './requestTaskPayload';
import { ServiceContactDetails } from './serviceContactDetails';

export interface EmpIssuanceUkEtsApplicationReviewRequestTaskPayload extends RequestTaskPayload {
  serviceContactDetails?: ServiceContactDetails;
  empSectionsCompleted?: { [key: string]: Array<boolean> };
  empAttachments?: { [key: string]: string };
  emissionsMonitoringPlan?: EmissionsMonitoringPlanUkEts;
  determination?: EmpIssuanceDetermination;
  reviewSectionsCompleted?: { [key: string]: boolean };
  reviewGroupDecisions?: { [key: string]: EmpIssuanceReviewDecision };
  reviewAttachments?: { [key: string]: string };
  rfiAttachments?: { [key: string]: string };
}
