/**
 * PMRV API Documentation
 * PMRV API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EmissionsMonitoringPlanCorsia } from './emissionsMonitoringPlanCorsia';
import { EmissionsMonitoringPlanCorsiaContainer } from './emissionsMonitoringPlanCorsiaContainer';
import { EmpVariationCorsiaDetails } from './empVariationCorsiaDetails';
import { EmpVariationDetermination } from './empVariationDetermination';
import { EmpVariationReviewDecision } from './empVariationReviewDecision';
import { RequestTaskPayload } from './requestTaskPayload';
import { ServiceContactDetails } from './serviceContactDetails';

export interface EmpVariationCorsiaApplicationAmendsSubmitRequestTaskPayload extends RequestTaskPayload {
  empSectionsCompleted?: { [key: string]: Array<boolean> };
  empAttachments?: { [key: string]: string };
  emissionsMonitoringPlan?: EmissionsMonitoringPlanCorsia;
  serviceContactDetails?: ServiceContactDetails;
  empVariationDetails?: EmpVariationCorsiaDetails;
  empVariationDetailsCompleted?: boolean;
  reviewSectionsCompleted?: { [key: string]: boolean };
  originalEmpContainer?: EmissionsMonitoringPlanCorsiaContainer;
  empVariationDetailsReviewDecision?: EmpVariationReviewDecision;
  empVariationDetailsReviewCompleted?: boolean;
  reviewGroupDecisions?: { [key: string]: EmpVariationReviewDecision };
  determination?: EmpVariationDetermination;
  reviewAttachments?: { [key: string]: string };
  rfiAttachments?: { [key: string]: string };
  empVariationDetailsAmendCompleted?: boolean;
}
