/**
 * METS API Documentation
 * METS API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EmissionsMonitoringPlanUkEts } from './emissionsMonitoringPlanUkEts';
import { EmissionsMonitoringPlanUkEtsContainer } from './emissionsMonitoringPlanUkEtsContainer';
import { EmpAcceptedVariationDecisionDetails } from './empAcceptedVariationDecisionDetails';
import { EmpVariationUkEtsDetails } from './empVariationUkEtsDetails';
import { EmpVariationUkEtsRegulatorLedReason } from './empVariationUkEtsRegulatorLedReason';
import { ServiceContactDetails } from './serviceContactDetails';

export interface EmpVariationUkEtsApplicationSubmitRegulatorLedRequestTaskPayloadAllOf {
  empSectionsCompleted?: { [key: string]: Array<boolean> };
  empAttachments?: { [key: string]: string };
  emissionsMonitoringPlan?: EmissionsMonitoringPlanUkEts;
  serviceContactDetails?: ServiceContactDetails;
  empVariationDetails?: EmpVariationUkEtsDetails;
  empVariationDetailsCompleted?: boolean;
  originalEmpContainer?: EmissionsMonitoringPlanUkEtsContainer;
  reasonRegulatorLed?: EmpVariationUkEtsRegulatorLedReason;
  reviewGroupDecisions?: { [key: string]: EmpAcceptedVariationDecisionDetails };
}
