/**
 * METS API Documentation
 * METS API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EmissionsMonitoringPlanUkEts } from './emissionsMonitoringPlanUkEts';
import { EmpVariationUkEtsDetails } from './empVariationUkEtsDetails';

export interface EmpVariationUkEtsSaveApplicationAmendRequestTaskActionPayloadAllOf {
  emissionsMonitoringPlan?: EmissionsMonitoringPlanUkEts;
  empVariationDetails?: EmpVariationUkEtsDetails;
  empVariationDetailsCompleted?: boolean;
  empSectionsCompleted?: { [key: string]: Array<boolean> };
  reviewSectionsCompleted?: { [key: string]: boolean };
  empVariationDetailsReviewCompleted?: boolean;
  empVariationDetailsAmendCompleted?: boolean;
}
