/**
 * METS API Documentation
 * METS API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EmissionsMonitoringPlanCorsia } from './emissionsMonitoringPlanCorsia';
import { EmpVariationCorsiaDetails } from './empVariationCorsiaDetails';
import { RequestTaskPayload } from './requestTaskPayload';
import { ServiceContactDetails } from './serviceContactDetails';

export interface EmpVariationCorsiaApplicationSubmitRequestTaskPayload extends RequestTaskPayload {
  empSectionsCompleted?: { [key: string]: Array<boolean> };
  empAttachments?: { [key: string]: string };
  emissionsMonitoringPlan?: EmissionsMonitoringPlanCorsia;
  serviceContactDetails?: ServiceContactDetails;
  empVariationDetails?: EmpVariationCorsiaDetails;
  empVariationDetailsCompleted?: boolean;
  reviewSectionsCompleted?: { [key: string]: boolean };
}
