/**
 * METS API Documentation
 * METS API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface EmpVariationUkEtsDetails {
  reason: string;
  changes: Array<
    | 'EMISSION_FACTOR_VALUES'
    | 'METHOD_USED_TO_CALCULATE_EMISSIONS_FACTOR'
    | 'DIFFERENT_FUMMS'
    | 'FUMM_TO_ESTIMATION_METHOD'
    | 'NEW_FUEL_TYPE'
    | 'SMALL_EMITTER_STATUS_OR_EMISSIONS_THRESHOLD_STATUS'
    | 'LEGAL_ENTITY_NAME'
    | 'REGISTERED_OFFICE_ADDRESS'
    | 'OTHER'
  >;
}
