/**
 * METS API Documentation
 * METS API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface FollowUpAction {
  followUpActionType:
    | 'MISSTATEMENT'
    | 'NON_CONFORMITY'
    | 'NON_COMPLIANCE'
    | 'RECOMMENDED_IMPROVEMENT'
    | 'UNRESOLVED_ISSUE_FROM_PREVIOUS_AUDIT';
  explanation: string;
  followUpActionAttachments?: Array<string>;
}
