/**
 * METS API Documentation
 * METS API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DecisionNotification } from './decisionNotification';
import { FileInfoDTO } from './fileInfoDTO';
import { HSETI } from './hSETI';
import { HSETIRegulatorReviewDecision } from './hSETIRegulatorReviewDecision';
import { HSETIRegulatorReviewOverallDecision } from './hSETIRegulatorReviewOverallDecision';
import { RequestActionPayload } from './requestActionPayload';
import { RequestActionUserInfo } from './requestActionUserInfo';

export interface HSETICompletedRequestActionPayload extends RequestActionPayload {
  hseti: HSETI;
  hsetiAttachments?: { [key: string]: string };
  decisionNotification?: DecisionNotification;
  officialNotice?: FileInfoDTO;
  usersInfo?: { [key: string]: RequestActionUserInfo };
  overallDecision: HSETIRegulatorReviewOverallDecision;
  regulatorReviewAttachments?: { [key: string]: string };
  regulatorReviewGroupDecisions?: { [key: string]: HSETIRegulatorReviewDecision };
}
