/**
 * METS API Documentation
 * METS API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HSETI } from './hSETI';
import { HSETIRegulatorReviewDecision } from './hSETIRegulatorReviewDecision';
import { HSETIRegulatorReviewOverallDecision } from './hSETIRegulatorReviewOverallDecision';

export interface HSETIApplicationRegulatorReviewSubmitRequestTaskPayloadAllOf {
  hseti?: HSETI;
  hsetiSectionsCompleted?: { [key: string]: boolean };
  hsetiAttachments?: { [key: string]: string };
  overallDecision?: HSETIRegulatorReviewOverallDecision;
  regulatorReviewSectionsCompleted?: { [key: string]: boolean };
  regulatorReviewAttachments?: { [key: string]: string };
  regulatorReviewGroupDecisions?: { [key: string]: HSETIRegulatorReviewDecision };
}
