/**
 * METS API Documentation
 * METS API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RequestCreateActionPayload } from './requestCreateActionPayload';

export interface HSETIRequestCreateActionPayload extends RequestCreateActionPayload {
  allocationPeriod?: 'PERIOD_2021_2025' | 'PERIOD_2026_2030';
}
