/**
 * METS API Documentation
 * METS API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface InherentReceivingTransferringInstallation {
  inherentCO2Direction:
    | 'EXPORTED_TO_ETS_INSTALLATION'
    | 'EXPORTED_TO_NON_ETS_CONSUMER'
    | 'RECEIVED_FROM_ANOTHER_INSTALLATION';
  installationDetailsType: 'INSTALLATION_EMITTER' | 'INSTALLATION_DETAILS';
  inherentReceivingTransferringInstallationDetailsType: object;
  measurementInstrumentOwnerTypes: Array<
    'INSTRUMENTS_BELONGING_TO_YOUR_INSTALLATION' | 'INSTRUMENTS_BELONGING_TO_THE_OTHER_INSTALLATION'
  >;
  totalEmissions: string;
}
