/**
 * METS API Documentation
 * METS API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BusinessOrganisationDetails } from './businessOrganisationDetails';
import { IndividualOrganisationDetails } from './individualOrganisationDetails';
import { RegistryIntegrationAccountUpdateActivePermit } from './registryIntegrationAccountUpdateActivePermit';
import { RequestActionPayload } from './requestActionPayload';

export interface InstallationAccountUpdatedRegistryIntegrationRequestActionPayload extends RequestActionPayload {
  activePermit?: RegistryIntegrationAccountUpdateActivePermit;
  organizationDetails?: BusinessOrganisationDetails | IndividualOrganisationDetails;
}
