/**
 * METS API Documentation
 * METS API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InstallationAccountSubmitter } from './installationAccountSubmitter';
import { LegalEntityDTO } from './legalEntityDTO';
import { LocationDTO } from './locationDTO';
import { LocationOffShoreDTO } from './locationOffShoreDTO';
import { LocationOnShoreDTO } from './locationOnShoreDTO';
import { LocationOnShoreStateDTO } from './locationOnShoreStateDTO';

export interface InstallationAccountOpeningAmendApplicationRequestTaskActionPayloadAllOf {
  accountType?: 'INSTALLATION' | 'AVIATION';
  applicationType?: 'NEW_PERMIT' | 'TRANSFER';
  name?: string;
  submitter?: InstallationAccountSubmitter;
  siteName?: string;
  emissionTradingScheme?: 'UK_ETS_INSTALLATIONS' | 'EU_ETS_INSTALLATIONS' | 'UK_ETS_AVIATION' | 'CORSIA';
  competentAuthority?: 'ENGLAND' | 'NORTHERN_IRELAND' | 'OPRED' | 'SCOTLAND' | 'WALES';
  commencementDate?: string;
  legalEntity?: LegalEntityDTO;
  location?: LocationDTO | LocationOffShoreDTO | LocationOnShoreDTO | LocationOnShoreStateDTO;
}
