/**
 * METS API Documentation
 * METS API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface LimeDataSource {
  dataSourceNo: string;
  detail:
    | 'CALCULATION_METHOD_MONITORING_PLAN'
    | 'LABORATORY_ANALYSES_SECTION_61'
    | 'SIMPLIFIED_LABORATORY_ANALYSES_SECTION_62'
    | 'CONSTANT_VALUES_STANDARD_SUPPLIER'
    | 'CONSTANT_VALUES_SCIENTIFIC_EVIDENCE';
}
