/**
 * PMRV API Documentation
 * PMRV API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TransferCO2 } from './transferCO2';

export interface MeasurementOfCO2EmissionPointCategory {
  emissionPoint: string;
  sourceStreams: Array<string>;
  emissionSources: Array<string>;
  annualEmittedCO2Tonnes: string;
  categoryType: 'MAJOR' | 'MINOR' | 'DE_MINIMIS' | 'MARGINAL';
  transfer?: TransferCO2;
}
