/**
 * METS API Documentation
 * METS API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AppliedStandard } from './appliedStandard';
import { MeasurementBiomassFraction } from './measurementBiomassFraction';
import { MeasurementOfCO2EmissionPointCategory } from './measurementOfCO2EmissionPointCategory';
import { MeasurementOfCO2MeasuredEmissions } from './measurementOfCO2MeasuredEmissions';

export interface MeasurementOfCO2EmissionPointCategoryAppliedTier {
  emissionPointCategory: MeasurementOfCO2EmissionPointCategory;
  measuredEmissions: MeasurementOfCO2MeasuredEmissions;
  appliedStandard: AppliedStandard;
  biomassFraction: MeasurementBiomassFraction;
}
