/**
 * METS API Documentation
 * METS API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MeasurementOfCO2EmissionPointCategoryAppliedTier } from './measurementOfCO2EmissionPointCategoryAppliedTier';
import { ProcedureForm } from './procedureForm';
import { ProcedureOptionalForm } from './procedureOptionalForm';

export interface MeasurementOfCO2MonitoringApproachAllOf {
  hasTransfer?: boolean;
  approachDescription?: string;
  emissionDetermination?: ProcedureForm;
  referencePeriodDetermination?: ProcedureForm;
  gasFlowCalculation?: ProcedureOptionalForm;
  biomassEmissions?: ProcedureOptionalForm;
  corroboratingCalculations?: ProcedureForm;
  emissionPointCategoryAppliedTiers?: Array<MeasurementOfCO2EmissionPointCategoryAppliedTier>;
}
