/**
 * PMRV API Documentation
 * PMRV API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TransferN2O } from './transferN2O';

export interface MeasurementOfN2OEmissionPointCategory {
  emissionPoint: string;
  sourceStreams: Array<string>;
  emissionSources: Array<string>;
  annualEmittedCO2Tonnes: string;
  categoryType: 'MAJOR' | 'MINOR' | 'DE_MINIMIS' | 'MARGINAL';
  emissionType: 'ABATED' | 'UNABATED';
  monitoringApproachType: 'CALCULATION' | 'MEASUREMENT';
  transfer?: TransferN2O;
}
