/**
 * METS API Documentation
 * METS API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NER } from './nER';
import { RequestTaskPayload } from './requestTaskPayload';

export interface NerApplicationSubmitRequestTaskPayload extends RequestTaskPayload {
  ner?: NER;
  verificationSectionsCompleted?: { [key: string]: Array<boolean> };
  regulatorReviewSectionsCompleted?: { [key: string]: boolean };
  nerSectionsCompleted?: { [key: string]: boolean };
  nerAttachments?: { [key: string]: string };
  nerFileVersion?: number;
  verificationPerformed?: boolean;
  verificationBodyId?: number;
}
