/**
 * METS API Documentation
 * METS API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NERNotVerifiedOverallVerificationAssessment } from './nERNotVerifiedOverallVerificationAssessment';
import { NERVerificationOpinionStatement } from './nERVerificationOpinionStatement';
import { NERVerifiedSatisfactoryOverallVerificationAssessment } from './nERVerifiedSatisfactoryOverallVerificationAssessment';
import { NERVerifiedWithCommentsOverallVerificationAssessment } from './nERVerifiedWithCommentsOverallVerificationAssessment';
import { RequestTaskActionPayload } from './requestTaskActionPayload';

export interface NERApplicationVerificationSaveRequestTaskActionPayload extends RequestTaskActionPayload {
  opinionStatement?: NERVerificationOpinionStatement;
  overallAssessment?:
    | NERNotVerifiedOverallVerificationAssessment
    | NERVerifiedSatisfactoryOverallVerificationAssessment
    | NERVerifiedWithCommentsOverallVerificationAssessment;
  verificationSectionsCompleted?: { [key: string]: Array<boolean> };
}
