/**
 * PMRV API Documentation
 * PMRV API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DecisionNotification } from './decisionNotification';
import { GrantAuthorityResponse } from './grantAuthorityResponse';
import { RequestActionUserInfo } from './requestActionUserInfo';

export interface NerApplicationAcceptedRequestActionPayloadAllOf {
  submittedToAuthorityDate?: string;
  authorityResponse?: GrantAuthorityResponse;
  nerAttachments?: { [key: string]: string };
  decisionNotification?: DecisionNotification;
  usersInfo?: { [key: string]: RequestActionUserInfo };
}
