/**
 * METS API Documentation
 * METS API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NER } from './nER';
import { NERApplicationRegulatorReviewOutcome } from './nERApplicationRegulatorReviewOutcome';
import { NERNerDataRegulatorReviewDecision } from './nERNerDataRegulatorReviewDecision';
import { NERReviewDecision } from './nERReviewDecision';
import { NERVerificationReport } from './nERVerificationReport';
import { NERVerificationReportDataRegulatorReviewDecision } from './nERVerificationReportDataRegulatorReviewDecision';

export interface NERApplicationRegulatorReviewSubmitRequestTaskPayloadAllOf {
  ner?: NER;
  verificationSectionsCompleted?: { [key: string]: Array<boolean> };
  regulatorReviewSectionsCompleted?: { [key: string]: boolean };
  nerSectionsCompleted?: { [key: string]: boolean };
  nerAttachments?: { [key: string]: string };
  nerFileVersion?: number;
  verificationReport?: NERVerificationReport;
  verificationAttachments?: { [key: string]: string };
  verifiedNER?: NER;
  regulatorReviewOutcome?: NERApplicationRegulatorReviewOutcome;
  regulatorReviewGroupDecisions?: {
    [key: string]:
      | NERReviewDecision
      | NERNerDataRegulatorReviewDecision
      | NERVerificationReportDataRegulatorReviewDecision;
  };
  regulatorReviewAttachments?: { [key: string]: string };
}
