/**
 * METS API Documentation
 * METS API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NERRegulatorReviewDecisionDetails } from './nERRegulatorReviewDecisionDetails';
import { NERReviewDecision } from './nERReviewDecision';

export interface NERNerDataRegulatorReviewDecision extends NERReviewDecision {
  type: 'ACCEPTED' | 'OPERATOR_AMENDS_NEEDED';
  details?: NERRegulatorReviewDecisionDetails;
}
