/**
 * METS API Documentation
 * METS API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ActivityLevel } from './activityLevel';
import { PreliminaryAllocation } from './preliminaryAllocation';

export interface NerProceedToAuthorityDetermination {
  type: 'CLOSED' | 'DEEMED_WITHDRAWN' | 'PROCEED_TO_AUTHORITY';
  reason: string;
  newEntrantType: 'YEAR_0' | 'YEAR_0_PLUS_1';
  operationStartDate: string;
  activityLevels?: Array<ActivityLevel>;
  preliminaryAllocations?: Array<PreliminaryAllocation>;
  sendOfficialNotice: boolean;
}
