/**
 * METS API Documentation
 * METS API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdditionalDocuments } from './additionalDocuments';
import { ConfidentialityStatement } from './confidentialityStatement';
import { RequestTaskActionPayload } from './requestTaskActionPayload';

export interface NerSaveApplicationReviewRequestTaskActionPayload extends RequestTaskActionPayload {
  newEntrantDataReport?: string;
  verifierOpinionStatement?: string;
  monitoringMethodologyPlan?: string;
  confidentialityStatement?: ConfidentialityStatement;
  additionalDocuments?: AdditionalDocuments;
  nerSectionsCompleted?: { [key: string]: boolean };
  reviewSectionsCompleted?: { [key: string]: boolean };
}
