/**
 * METS API Documentation
 * METS API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RequestActionPayload } from './requestActionPayload';
import { RequestActionUserInfo } from './requestActionUserInfo';

export interface NonComplianceDailyPenaltyNoticeApplicationSubmittedRequestActionPayload extends RequestActionPayload {
  dailyPenaltyNotice: string;
  comments?: string;
  operators?: Array<string>;
  externalContacts?: Array<number>;
  nonComplianceAttachments?: { [key: string]: string };
  usersInfo?: { [key: string]: RequestActionUserInfo };
}
