/**
 * METS API Documentation
 * METS API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NonComplianceCloseJustification } from './nonComplianceCloseJustification';

export interface NonComplianceFinalDeterminationRequestTaskPayloadAllOf {
  complianceRestored?: boolean;
  complianceRestoredDate?: string;
  comments?: string;
  reissuePenalty?: boolean;
  operatorPaid?: boolean;
  operatorPaidDate?: string;
  closeJustification?: NonComplianceCloseJustification;
  nonComplianceAttachments?: { [key: string]: string };
  determinationCompleted?: boolean;
}
