/**
 * PMRV API Documentation
 * PMRV API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface PaymentProcessedRequestActionPayloadAllOf {
  paymentCreationDate?: string;
  paymentRefNum?: string;
  amount?: string;
  status?: 'MARK_AS_PAID' | 'MARK_AS_RECEIVED' | 'COMPLETED' | 'CANCELLED';
  paymentMethod?: 'BANK_TRANSFER' | 'CREDIT_OR_DEBIT_CARD';
  paidByFullName?: string;
  receivedDate?: string;
  paymentDate?: string;
}
