/**
 * METS API Documentation
 * METS API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface PermanentCessation {
  description: string;
  files?: Array<string>;
  cessationDate: string;
  cessationScope: 'WHOLE_INSTALLATION' | 'SUB_INSTALLATIONS_ONLY';
  additionalDetails: string;
  regulatorComments?: string;
}
