/**
 * METS API Documentation
 * METS API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface PermitTransferASaveApplicationRequestTaskActionPayloadAllOf {
  reason?: string;
  reasonAttachments?: Array<string>;
  transferDate?: string;
  payer?: 'TRANSFERER' | 'RECEIVER';
  aerLiable?: 'TRANSFERER' | 'RECEIVER';
  transferCode?: string;
  sectionCompleted?: boolean;
}
