/**
 * METS API Documentation
 * METS API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface PermitSurrenderReviewDeterminationGrantAllOf {
  stopDate?: string;
  noticeDate?: string;
  reportRequired?: boolean;
  reportDate?: string;
  alrRequired?: boolean;
  alrReportDate?: string;
  allowancesSurrenderRequired?: boolean;
  allowancesSurrenderDate?: string;
}
