/**
 * PMRV API Documentation
 * PMRV API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PermitNotification } from './permitNotification';
import { PermitNotificationReviewDecision } from './permitNotificationReviewDecision';
import { RequestTaskPayload } from './requestTaskPayload';

export interface PermitNotificationApplicationReviewRequestTaskPayload extends RequestTaskPayload {
  permitNotification: PermitNotification;
  permitNotificationAttachments?: { [key: string]: string };
  reviewDecision: PermitNotificationReviewDecision;
  rfiAttachments?: { [key: string]: string };
}
