/**
 * PMRV API Documentation
 * PMRV API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DecisionNotification } from './decisionNotification';
import { FileInfoDTO } from './fileInfoDTO';
import { InstallationOperatorDetails } from './installationOperatorDetails';
import { Permit } from './permit';
import { PermitAcceptedVariationDecisionDetails } from './permitAcceptedVariationDecisionDetails';
import { PermitContainer } from './permitContainer';
import { PermitVariationDetails } from './permitVariationDetails';
import { PermitVariationRegulatorLedGrantDetermination } from './permitVariationRegulatorLedGrantDetermination';
import { RequestActionPayload } from './requestActionPayload';
import { RequestActionUserInfo } from './requestActionUserInfo';

export interface PermitVariationApplicationRegulatorLedApprovedRequestActionPayload extends RequestActionPayload {
  permitType: 'GHGE' | 'HSE';
  installationOperatorDetails: InstallationOperatorDetails;
  permit: Permit;
  permitVariationDetails: PermitVariationDetails;
  permitAttachments?: { [key: string]: string };
  permitSectionsCompleted?: { [key: string]: Array<boolean> };
  originalPermitContainer?: PermitContainer;
  permitVariationDetailsReviewDecision?: PermitAcceptedVariationDecisionDetails;
  reviewGroupDecisions?: { [key: string]: PermitAcceptedVariationDecisionDetails };
  determination?: PermitVariationRegulatorLedGrantDetermination;
  decisionNotification: DecisionNotification;
  usersInfo?: { [key: string]: RequestActionUserInfo };
  officialNotice: FileInfoDTO;
  permitDocument: FileInfoDTO;
}
