/**
 * PMRV API Documentation
 * PMRV API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PermitNotificationFollowUpReviewDecision } from './permitNotificationFollowUpReviewDecision';

export interface PermitNotificationFollowUpApplicationAmendsSubmitRequestTaskPayloadAllOf {
  followUpRequest?: string;
  followUpResponseExpirationDate?: string;
  followUpResponse?: string;
  followUpFiles?: Array<string>;
  followUpAttachments?: { [key: string]: string };
  permitNotificationType?:
    | 'TEMPORARY_FACTOR'
    | 'TEMPORARY_CHANGE'
    | 'TEMPORARY_SUSPENSION'
    | 'NON_SIGNIFICANT_CHANGE'
    | 'OTHER_FACTOR';
  submissionDate?: string;
  reviewDecision?: PermitNotificationFollowUpReviewDecision;
  reviewSectionsCompleted?: { [key: string]: boolean };
  followUpSectionsCompleted?: { [key: string]: boolean };
}
