/**
 * PMRV API Documentation
 * PMRV API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Abbreviations } from './abbreviations';
import { AdditionalDocuments } from './additionalDocuments';
import { ConfidentialityStatement } from './confidentialityStatement';
import { DataFlowActivities } from './dataFlowActivities';
import { EmissionPoint } from './emissionPoint';
import { EmissionSource } from './emissionSource';
import { EmissionSummary } from './emissionSummary';
import { EnvironmentalManagementSystem } from './environmentalManagementSystem';
import { EnvironmentalPermitsAndLicences } from './environmentalPermitsAndLicences';
import { EstimatedAnnualEmissions } from './estimatedAnnualEmissions';
import { InstallationDescription } from './installationDescription';
import { ManagementProceduresDefinition } from './managementProceduresDefinition';
import { MeasurementDeviceOrMethod } from './measurementDeviceOrMethod';
import { MonitoringMethodologyPlans } from './monitoringMethodologyPlans';
import { MonitoringReporting } from './monitoringReporting';
import { PermitMonitoringApproachSection } from './permitMonitoringApproachSection';
import { RegulatedActivity } from './regulatedActivity';
import { SourceStream } from './sourceStream';
import { UncertaintyAnalysis } from './uncertaintyAnalysis';

export interface Permit {
  environmentalPermitsAndLicences: EnvironmentalPermitsAndLicences;
  estimatedAnnualEmissions: EstimatedAnnualEmissions;
  installationDescription: InstallationDescription;
  regulatedActivities: Array<RegulatedActivity>;
  monitoringMethodologyPlans: MonitoringMethodologyPlans;
  sourceStreams: Array<SourceStream>;
  measurementDevicesOrMethods: Array<MeasurementDeviceOrMethod>;
  emissionSources: Array<EmissionSource>;
  emissionPoints: Array<EmissionPoint>;
  emissionSummaries: Array<EmissionSummary>;
  siteDiagrams?: Array<string>;
  abbreviations: Abbreviations;
  confidentialityStatement: ConfidentialityStatement;
  additionalDocuments: AdditionalDocuments;
  monitoringApproaches: { [key: string]: PermitMonitoringApproachSection };
  uncertaintyAnalysis: UncertaintyAnalysis;
  monitoringReporting: MonitoringReporting;
  assignmentOfResponsibilities: ManagementProceduresDefinition;
  monitoringPlanAppropriateness: ManagementProceduresDefinition;
  dataFlowActivities: DataFlowActivities;
  qaDataFlowActivities: ManagementProceduresDefinition;
  reviewAndValidationOfData: ManagementProceduresDefinition;
  assessAndControlRisk: ManagementProceduresDefinition;
  qaMeteringAndMeasuringEquipment: ManagementProceduresDefinition;
  correctionsAndCorrectiveActions: ManagementProceduresDefinition;
  controlOfOutsourcedActivities: ManagementProceduresDefinition;
  recordKeepingAndDocumentation: ManagementProceduresDefinition;
  environmentalManagementSystem: EnvironmentalManagementSystem;
}
