/**
 * PMRV API Documentation
 * PMRV API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DecisionNotification } from './decisionNotification';
import { PermitNotificationFollowUpReviewDecision } from './permitNotificationFollowUpReviewDecision';
import { RequestActionPayload } from './requestActionPayload';
import { RequestActionUserInfo } from './requestActionUserInfo';

export interface PermitNotificationFollowUpApplicationReviewSubmittedDecisionRequestActionPayload
  extends RequestActionPayload {
  permitNotificationType:
    | 'TEMPORARY_FACTOR'
    | 'TEMPORARY_CHANGE'
    | 'TEMPORARY_SUSPENSION'
    | 'NON_SIGNIFICANT_CHANGE'
    | 'OTHER_FACTOR';
  request: string;
  responseExpirationDate: string;
  response: string;
  responseFiles?: Array<string>;
  responseAttachments?: { [key: string]: string };
  responseSubmissionDate: string;
  reviewDecision: PermitNotificationFollowUpReviewDecision;
  reviewDecisionNotification: DecisionNotification;
  usersInfo?: { [key: string]: RequestActionUserInfo };
}
