/**
 * METS API Documentation
 * METS API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InstallationOperatorDetails } from './installationOperatorDetails';
import { Permit } from './permit';
import { PermitIssuanceDeterminateable } from './permitIssuanceDeterminateable';
import { PermitIssuanceReviewDecision } from './permitIssuanceReviewDecision';
import { PermitTransferBDetailsConfirmationReviewDecision } from './permitTransferBDetailsConfirmationReviewDecision';
import { PermitTransferDetails } from './permitTransferDetails';
import { PermitTransferDetailsConfirmation } from './permitTransferDetailsConfirmation';

export interface PermitTransferBApplicationReviewRequestTaskPayloadAllOf {
  permitType?: 'GHGE' | 'HSE' | 'WASTE';
  permit?: Permit;
  installationOperatorDetails?: InstallationOperatorDetails;
  permitSectionsCompleted?: { [key: string]: Array<boolean> };
  permitAttachments?: { [key: string]: string };
  reviewSectionsCompleted?: { [key: string]: boolean };
  reviewGroupDecisions?: { [key: string]: PermitIssuanceReviewDecision };
  reviewAttachments?: { [key: string]: string };
  determination?: PermitIssuanceDeterminateable;
  rfiAttachments?: { [key: string]: string };
  permitTransferDetails?: PermitTransferDetails;
  permitTransferDetailsConfirmation?: PermitTransferDetailsConfirmation;
  permitTransferDetailsConfirmationDecision?: PermitTransferBDetailsConfirmationReviewDecision;
}
