/**
 * PMRV API Documentation
 * PMRV API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InstallationOperatorDetails } from './installationOperatorDetails';
import { Permit } from './permit';
import { PermitContainer } from './permitContainer';
import { PermitVariationDetails } from './permitVariationDetails';
import { PermitVariationDeterminateable } from './permitVariationDeterminateable';
import { PermitVariationReviewDecision } from './permitVariationReviewDecision';
import { RequestTaskPayload } from './requestTaskPayload';

export interface PermitVariationApplicationReviewRequestTaskPayload extends RequestTaskPayload {
  permitType?: 'GHGE' | 'HSE';
  permit?: Permit;
  installationOperatorDetails?: InstallationOperatorDetails;
  permitVariationDetails?: PermitVariationDetails;
  permitVariationDetailsCompleted?: boolean;
  permitSectionsCompleted?: { [key: string]: Array<boolean> };
  permitAttachments?: { [key: string]: string };
  reviewSectionsCompleted?: { [key: string]: boolean };
  originalPermitContainer?: PermitContainer;
  permitVariationDetailsReviewDecision?: PermitVariationReviewDecision;
  permitVariationDetailsReviewCompleted?: boolean;
  reviewGroupDecisions?: { [key: string]: PermitVariationReviewDecision };
  determination?: PermitVariationDeterminateable;
  reviewAttachments?: { [key: string]: string };
  rfiAttachments?: { [key: string]: string };
}
