/**
 * METS API Documentation
 * METS API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DecisionNotification } from './decisionNotification';
import { FileInfoDTO } from './fileInfoDTO';
import { PermitNotification } from './permitNotification';
import { PermitNotificationReviewDecision } from './permitNotificationReviewDecision';
import { RequestActionUserInfo } from './requestActionUserInfo';

export interface PermitNotificationApplicationReviewCompletedDecisionRequestActionPayloadAllOf {
  reviewDecision?: PermitNotificationReviewDecision;
  reviewDecisionNotification?: DecisionNotification;
  usersInfo?: { [key: string]: RequestActionUserInfo };
  officialNotice?: FileInfoDTO;
  permitNotification?: PermitNotification;
  permitNotificationAttachments?: { [key: string]: string };
}
