/**
 * METS API Documentation
 * METS API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface PFCSourceStreamCategory {
  sourceStream: string;
  emissionSources: Array<string>;
  annualEmittedCO2Tonnes: string;
  categoryType: 'MAJOR' | 'MINOR' | 'DE_MINIMIS' | 'MARGINAL';
  emissionPoints: Array<string>;
  calculationMethod: 'SLOPE' | 'OVERVOLTAGE';
}
