/**
 * METS API Documentation
 * METS API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The search criteria
 */
export interface RequestSearchCriteria {
  resourceType: string;
  resourceId: string;
  requestTypes?: Array<
    | 'INSTALLATION_ACCOUNT_OPENING'
    | 'SYSTEM_MESSAGE_NOTIFICATION'
    | 'PERMIT_ISSUANCE'
    | 'PERMIT_SURRENDER'
    | 'PERMIT_REVOCATION'
    | 'PERMIT_TRANSFER_A'
    | 'PERMIT_TRANSFER_B'
    | 'PERMIT_VARIATION'
    | 'PERMIT_NOTIFICATION'
    | 'PERMIT_BATCH_REISSUE'
    | 'PERMIT_REISSUE'
    | 'NON_COMPLIANCE'
    | 'NER'
    | 'DOAL'
    | 'AER'
    | 'VIR'
    | 'AIR'
    | 'DRE'
    | 'WITHHOLDING_OF_ALLOWANCES'
    | 'RETURN_OF_ALLOWANCES'
    | 'INSTALLATION_ONSITE_INSPECTION'
    | 'INSTALLATION_AUDIT'
    | 'BDR'
    | 'PERMANENT_CESSATION'
    | 'ALR'
    | 'AVIATION_ACCOUNT_CLOSURE'
    | 'AVIATION_NON_COMPLIANCE'
    | 'EMP_BATCH_REISSUE'
    | 'EMP_REISSUE'
    | 'AVIATION_VIR'
    | 'EMP_ISSUANCE_UKETS'
    | 'EMP_VARIATION_UKETS'
    | 'AVIATION_AER_UKETS'
    | 'AVIATION_DRE_UKETS'
    | 'EMP_ISSUANCE_CORSIA'
    | 'EMP_VARIATION_CORSIA'
    | 'AVIATION_AER_CORSIA'
    | 'AVIATION_DOE_CORSIA'
    | 'AVIATION_AER_CORSIA_ANNUAL_OFFSETTING'
    | 'AVIATION_AER_CORSIA_3YEAR_PERIOD_OFFSETTING'
  >;
  requestStatuses?: Array<
    | 'IN_PROGRESS'
    | 'COMPLETED'
    | 'CANCELLED'
    | 'WITHDRAWN'
    | 'APPROVED'
    | 'REJECTED'
    | 'CLOSED'
    | 'EXEMPT'
    | 'MIGRATED'
    | 'NOT_REQUIRED'
  >;
  category: 'PERMIT' | 'REPORTING' | 'INSPECTION' | 'CA';
  pageNumber: number;
  pageSize: number;
}
