/**
 * METS API Documentation
 * METS API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface RequestMetadata {
  type?:
    | 'PERMIT_ISSUANCE'
    | 'PERMIT_SURRENDER'
    | 'PERMIT_VARIATION'
    | 'PERMIT_NOTIFICATION'
    | 'PERMIT_TRANSFER_B'
    | 'PERMIT_BATCH_REISSUE'
    | 'DOAL'
    | 'AER'
    | 'VIR'
    | 'DRE'
    | 'AIR'
    | 'INSTALLATION_INSPECTION'
    | 'BDR'
    | 'PERMANENT_CESSATION'
    | 'ALR'
    | 'REISSUE'
    | 'AVIATION_AER'
    | 'AVIATION_AER_CORSIA'
    | 'AVIATION_AER_CORSIA_ANNUAL_OFFSETTING'
    | 'AVIATION_AER_CORSIA_3YEAR_PERIOD_OFFSETTING'
    | 'AVIATION_DRE'
    | 'AVIATION_DOE_CORSIA'
    | 'AVIATION_VIR'
    | 'EMP_VARIATION'
    | 'EMP_BATCH_REISSUE';
}
