/**
 * PMRV API Documentation
 * PMRV API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RequestTaskActionPayload } from './requestTaskActionPayload';
import { ReturnOfAllowancesReturned } from './returnOfAllowancesReturned';

export interface ReturnOfAllowancesReturnedSaveApplicationRequestTaskActionPayload extends RequestTaskActionPayload {
  returnOfAllowancesReturned: ReturnOfAllowancesReturned;
  sectionsCompleted?: { [key: string]: boolean };
}
