/**
 * METS API Documentation
 * METS API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AnnualActivityFuelLevel } from './annualActivityFuelLevel';
import { AnnualActivityHeatLevel } from './annualActivityHeatLevel';
import { AnnualActivityProcessLevel } from './annualActivityProcessLevel';
import { AnnualProductionLevel } from './annualProductionLevel';
import { AromaticsSP } from './aromaticsSP';
import { DirectlyAttributableEmissionsFA } from './directlyAttributableEmissionsFA';
import { DirectlyAttributableEmissionsPB } from './directlyAttributableEmissionsPB';
import { DolimeSP } from './dolimeSP';
import { EthyleneOxideEthyleneGlycolsSP } from './ethyleneOxideEthyleneGlycolsSP';
import { FuelAndElectricityExchangeability } from './fuelAndElectricityExchangeability';
import { FuelInputAndRelevantEmissionFactorFA } from './fuelInputAndRelevantEmissionFactorFA';
import { FuelInputAndRelevantEmissionFactorHeatFA } from './fuelInputAndRelevantEmissionFactorHeatFA';
import { FuelInputAndRelevantEmissionFactorPB } from './fuelInputAndRelevantEmissionFactorPB';
import { HydrogenSP } from './hydrogenSP';
import { ImportedExportedMeasurableHeat } from './importedExportedMeasurableHeat';
import { ImportedMeasurableHeatFlow } from './importedMeasurableHeatFlow';
import { LimeSP } from './limeSP';
import { MeasurableHeat } from './measurableHeat';
import { RefineryProductsSP } from './refineryProductsSP';
import { SteamCrackingSP } from './steamCrackingSP';
import { SynthesisGasSP } from './synthesisGasSP';
import { VinylChlorideMonomerSP } from './vinylChlorideMonomerSP';
import { WasteGasBalance } from './wasteGasBalance';

export interface SubInstallation {
  subInstallationNo: string;
  subInstallationType:
    | 'PRIMARY_ALUMINIUM'
    | 'ADIPIC_ACID'
    | 'AMMONIA'
    | 'AROMATICS'
    | 'BOTTLES_AND_JARS_OF_COLOURED_GLASS'
    | 'BOTTLES_AND_JARS_OF_COLOURLESS_GLASS'
    | 'CARBON_BLACK'
    | 'COATED_CARTON_BOARD'
    | 'COATED_FINE_PAPER'
    | 'COKE'
    | 'CONTINUOUS_FILAMENT_GLASS_FIBRE_PRODUCTS'
    | 'DOLIME'
    | 'DRIED_SECONDARY_GYPSUM'
    | 'EAF_CARBON_STEEL'
    | 'EAF_HIGH_ALLOY_STEEL'
    | 'E_PVC'
    | 'ETHYLENE_OXIDE_ETHYLENE_GLYCOLS'
    | 'FACING_BRICKS'
    | 'FLOAT_GLASS'
    | 'GREY_CEMENT_CLINKER'
    | 'HOT_METAL'
    | 'HYDROGEN'
    | 'IRON_CASTING'
    | 'LIME'
    | 'LONG_FIBRE_KRAFT_PULP'
    | 'MINERAL_WOOL'
    | 'NEWSPRINT'
    | 'NITRIC_ACID'
    | 'PAVERS'
    | 'PHENOL_ACETONE'
    | 'PLASTER'
    | 'PLASTERBOARD'
    | 'PRE_BAKE_ANODE'
    | 'RECOVERED_PAPER_PULP'
    | 'REFINERY_PRODUCTS'
    | 'ROOF_TILES'
    | 'SHORT_FIBRE_KRAFT_PULP'
    | 'SINTERED_DOLIME'
    | 'SINTERED_ORE'
    | 'SODA_ASH'
    | 'SPRAY_DRIED_POWDER'
    | 'S_PVC'
    | 'STEAM_CRACKING'
    | 'STYRENE'
    | 'SULPHITE_PULP_THERMO_MECHANICAL_AND_MECHANICAL_PULP'
    | 'SYNTHESIS_GAS'
    | 'TESTLINER_AND_FLUTING'
    | 'TISSUE'
    | 'UNCOATED_CARTON_BOARD'
    | 'UNCOATED_FINE_PAPER'
    | 'VINYL_CHLORIDE_MONOMER'
    | 'WHITE_CEMENT_CLINKER'
    | 'HEAT_BENCHMARK_CL'
    | 'HEAT_BENCHMARK_NON_CL'
    | 'DISTRICT_HEATING_NON_CL'
    | 'FUEL_BENCHMARK_CL'
    | 'FUEL_BENCHMARK_NON_CL'
    | 'PROCESS_EMISSIONS_CL'
    | 'PROCESS_EMISSIONS_NON_CL';
  description: string;
  supportingFiles?: Array<string>;
  annualLevel: AnnualActivityFuelLevel | AnnualActivityHeatLevel | AnnualActivityProcessLevel | AnnualProductionLevel;
  fuelAndElectricityExchangeability?: FuelAndElectricityExchangeability;
  importedMeasurableHeatFlow?: ImportedMeasurableHeatFlow;
  directlyAttributableEmissions?: DirectlyAttributableEmissionsFA | DirectlyAttributableEmissionsPB;
  fuelInputAndRelevantEmissionFactor?:
    | FuelInputAndRelevantEmissionFactorFA
    | FuelInputAndRelevantEmissionFactorHeatFA
    | FuelInputAndRelevantEmissionFactorPB;
  importedExportedMeasurableHeat?: ImportedExportedMeasurableHeat;
  wasteGasBalance?: WasteGasBalance;
  specialProduct?:
    | AromaticsSP
    | DolimeSP
    | EthyleneOxideEthyleneGlycolsSP
    | HydrogenSP
    | LimeSP
    | RefineryProductsSP
    | SteamCrackingSP
    | SynthesisGasSP
    | VinylChlorideMonomerSP;
  measurableHeat?: MeasurableHeat;
}
