/**
 * METS API Documentation
 * METS API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface TechnicalCapabilityDetails {
  technicalCapability:
    | 'RESUME_REG_ACTIVITIES_WITHOUT_PHYSICAL_CHANGES'
    | 'RESTORE_TECHNICAL_CAPABILITY_TO_RESUME_REG_ACTIVITIES';
  details: string;
}
