/**
 * PMRV API Documentation
 * PMRV API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProcedureForm } from './procedureForm';
import { ProcedureOptionalForm } from './procedureOptionalForm';
import { TemperaturePressure } from './temperaturePressure';

export interface TransportCO2AndN2OPipelineSystems {
  exist?: boolean;
  procedureForLeakageEvents?: ProcedureOptionalForm;
  temperaturePressure?: TemperaturePressure;
  proceduresForTransferredCO2AndN2O?: ProcedureForm;
}
