/**
 * METS API Documentation
 * METS API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PermitMonitoringApproachSection } from './permitMonitoringApproachSection';
import { ProcedureOptionalForm } from './procedureOptionalForm';
import { TransportCO2AndN2OPipelineSystems } from './transportCO2AndN2OPipelineSystems';

export interface TransferredCO2AndN2OMonitoringApproach extends PermitMonitoringApproachSection {
  deductionsToAmountOfTransferredCO2: ProcedureOptionalForm;
  monitoringTransportNetworkApproach: 'METHOD_A' | 'METHOD_B';
  transportCO2AndN2OPipelineSystems: TransportCO2AndN2OPipelineSystems;
  geologicalStorage: ProcedureOptionalForm;
}
