/**
 * METS API Documentation
 * METS API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NotificationAlertDTO } from './notificationAlertDTO';

export interface UIPropertiesDTO {
  features?: { [key: string]: boolean };
  analytics?: { [key: string]: string };
  keycloakServerUrl?: string;
  notificationAlerts?: Array<NotificationAlertDTO>;
}
