/**
 * METS API Documentation
 * METS API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AddressDTO } from './addressDTO';
import { VerificationBodyEmissionSchemeDTO } from './verificationBodyEmissionSchemeDTO';

/**
 * The verification body dto to update
 */
export interface VerificationBodyUpdateDTO {
  id: number;
  name: string;
  address: AddressDTO;
  verificationBodyEmissionSchemes: Array<VerificationBodyEmissionSchemeDTO>;
}
