/**
 * PMRV API Documentation
 * PMRV API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OperatorImprovementResponse } from './operatorImprovementResponse';
import { RequestActionPayload } from './requestActionPayload';
import { VirVerificationData } from './virVerificationData';

export interface VirApplicationSubmittedRequestActionPayload extends RequestActionPayload {
  reportingYear: number;
  virAttachments?: { [key: string]: string };
  verificationData: VirVerificationData;
  operatorImprovementResponses: { [key: string]: OperatorImprovementResponse };
}
