/**
 * PMRV API Documentation
 * PMRV API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OperatorImprovementFollowUpResponse } from './operatorImprovementFollowUpResponse';
import { RequestTaskActionPayload } from './requestTaskActionPayload';

export interface VirSaveRespondToRegulatorCommentsRequestTaskActionPayload extends RequestTaskActionPayload {
  reference: string;
  virRespondToRegulatorCommentsSectionsCompleted?: { [key: string]: boolean };
  operatorImprovementFollowUpResponse: OperatorImprovementFollowUpResponse;
}
