/**
 * METS API Documentation
 * METS API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SubInstallationHierarchicalOrder } from './subInstallationHierarchicalOrder';
import { WasteGasFlowsDataSource } from './wasteGasFlowsDataSource';

export interface WasteGasFlows {
  wasteGasFlowsRelevant: boolean;
  wasteGasFlowsDataSources?: Array<WasteGasFlowsDataSource>;
  methodologyAppliedDescription?: string;
  hierarchicalOrder?: SubInstallationHierarchicalOrder;
  supportingFiles?: Array<string>;
}
