/**
 * METS API Documentation
 * METS API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WasteQDR } from './wasteQDR';
import { WasteQDRReviewDecision } from './wasteQDRReviewDecision';

export interface WasteQDRApplicationRegulatorReviewSubmitRequestTaskPayloadAllOf {
  qdr?: WasteQDR;
  reviewDecision?: WasteQDRReviewDecision;
  wasteQDRSectionsCompleted?: { [key: string]: boolean };
  wasteQDRAttachments?: { [key: string]: string };
  regulatorReviewSectionsCompleted?: { [key: string]: boolean };
  regulatorReviewAttachments?: { [key: string]: string };
}
