/**
 * METS API Documentation
 * METS API Documentation
 *
 * The version of the OpenAPI document: uk-pmrv-app-api 0.81.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RequestTaskPayload } from './requestTaskPayload';
import { WasteQDR } from './wasteQDR';
import { WasteQDRReviewDecision } from './wasteQDRReviewDecision';

export interface WasteQDRApplicationReviewRequestTaskPayload extends RequestTaskPayload {
  qdr?: WasteQDR;
  reviewDecision?: WasteQDRReviewDecision;
  wasteQDRAttachments?: { [key: string]: string };
  reviewSectionsCompleted?: { [key: string]: boolean };
  reviewAttachments?: { [key: string]: string };
}
