services:
  postgres-pmrv:
    image: postgres
    volumes:
      - postgres-data-pmrv:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: pmrv
      POSTGRES_USER: pmrv
      POSTGRES_PASSWORD: password
    ports:
      - 5433:5432

volumes:
  postgres-data-pmrv:
    driver: local
