package uk.gov.pmrv.api.workflow.request.core.domain.enumeration;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum RequestCustomContext {

	PERMIT_NOTIFICATION_FOLLOW_UP("PERMIT_NOTIFICATION_FOLLOW_UP"),
	PERMIT_VARIATION_REGULATOR_LED("PERMIT_VARIATION_REGULATOR_LED"),
	NON_COMPLIANCE_DAILY_PENALTY_NOTICE("NON_COMPLIANCE_DAILY_PENALTY_NOTICE"),
	NON_COMPLIANCE_NOTICE_OF_INTENT("NON_COMPLIANCE_NOTICE_OF_INTENT"),
	NON_COMPLIANCE_CIVIL_PENALTY("NON_COMPLIANCE_CIVIL_PENALTY"),
	AER_AMEND("AER_AMEND"),
	BDR_AMEND("BDR_AMEND"),
	EMP_VARIATION_UKETS_REGULATOR_LED("EMP_VARIATION_UKETS_REGULATOR_LED"),
	EMP_VARIATION_CORSIA_REGULATOR_LED("EMP_VARIATION_CORSIA_REGULATOR_LED"),
	
	AVIATION_NON_COMPLIANCE_DAILY_PENALTY_NOTICE("AVIATION_NON_COMPLIANCE_DAILY_PENALTY_NOTICE"),
	AVIATION_NON_COMPLIANCE_NOTICE_OF_INTENT("AVIATION_NON_COMPLIANCE_NOTICE_OF_INTENT"),
	AVIATION_NON_COMPLIANCE_CIVIL_PENALTY("AVIATION_NON_COMPLIANCE_CIVIL_PENALTY"),

	AVIATION_AER_UKETS_AMEND("AVIATION_AER_UKETS_AMEND"),
	AVIATION_AER_CORSIA_AMEND("AVIATION_AER_CORSIA_AMEND")
	;
	
	private final String code;
}
