package uk.gov.pmrv.api.workflow.request.core.domain.enumeration;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum RequestCreateActionType {

    INSTALLATION_ACCOUNT_OPENING_SUBMIT_APPLICATION(RequestType.INSTALLATION_ACCOUNT_OPENING),
    PERMIT_SURRENDER(RequestType.PERMIT_SURRENDER),
    PERMIT_REVOCATION(RequestType.PERMIT_REVOCATION),
    PERMIT_VARIATION(RequestType.PERMIT_VARIATION),
    PERMIT_TRANSFER_A(RequestType.PERMIT_TRANSFER_A),
    PERMIT_NOTIFICATION(RequestType.PERMIT_NOTIFICATION),
    PERMIT_BATCH_REISSUE(RequestType.PERMIT_BATCH_REISSUE),
    NON_COMPLIANCE(RequestType.NON_COMPLIANCE),
    NER(RequestType.NER),
    DOAL(RequestType.DOAL),
    INSTALLATION_ONSITE_INSPECTION(RequestType.INSTALLATION_ONSITE_INSPECTION),
    INSTALLATION_AUDIT(RequestType.INSTALLATION_AUDIT),
    AER(RequestType.AER),
    DRE(RequestType.DRE),
    WITHHOLDING_OF_ALLOWANCES(RequestType.WITHHOLDING_OF_ALLOWANCES),
    RETURN_OF_ALLOWANCES(RequestType.RETURN_OF_ALLOWANCES),
    AIR(RequestType.AIR),
    BDR(RequestType.BDR),
    PERMANENT_CESSATION(RequestType.PERMANENT_CESSATION),
    ALR(RequestType.ALR),

    EMP_BATCH_REISSUE(RequestType.EMP_BATCH_REISSUE),
    AVIATION_ACCOUNT_CLOSURE(RequestType.AVIATION_ACCOUNT_CLOSURE),
    EMP_VARIATION_UKETS(RequestType.EMP_VARIATION_UKETS),
    AVIATION_DRE_UKETS(RequestType.AVIATION_DRE_UKETS),
    AVIATION_NON_COMPLIANCE(RequestType.AVIATION_NON_COMPLIANCE),

    AVIATION_DOE_CORSIA(RequestType.AVIATION_DOE_CORSIA),
    AVIATION_AER_CORSIA_ANNUAL_OFFSETTING(RequestType.AVIATION_AER_CORSIA_ANNUAL_OFFSETTING),
    AVIATION_AER_CORSIA_3YEAR_PERIOD_OFFSETTING(RequestType.AVIATION_AER_CORSIA_3YEAR_PERIOD_OFFSETTING),

    EMP_VARIATION_CORSIA(RequestType.EMP_VARIATION_CORSIA),
    ;

    private final RequestType type;
}
