package uk.gov.pmrv.api.workflow.request.core.domain.enumeration;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum RequestPayloadType {

    INSTALLATION_ACCOUNT_OPENING_REQUEST_PAYLOAD,
    PERMIT_ISSUANCE_REQUEST_PAYLOAD,
    PERMIT_SURRENDER_REQUEST_PAYLOAD,
    PERMIT_NOTIFICATION_REQUEST_PAYLOAD,
    PERMIT_REVOCATION_REQUEST_PAYLOAD,
    PERMIT_VARIATION_REQUEST_PAYLOAD,
    PERMIT_TRANSFER_A_REQUEST_PAYLOAD,
    PERMIT_TRANSFER_B_REQUEST_PAYLOAD,
    PERMIT_BATCH_REISSUE_REQUEST_PAYLOAD,
    NON_COMPLIANCE_REQUEST_PAYLOAD,
    NER_REQUEST_PAYLOAD,
    DOAL_REQUEST_PAYLOAD,
    AER_REQUEST_PAYLOAD,
    VIR_REQUEST_PAYLOAD,
    DRE_REQUEST_PAYLOAD,
    AIR_REQUEST_PAYLOAD,

    REISSUE_REQUEST_PAYLOAD,
    SYSTEM_MESSAGE_NOTIFICATION_REQUEST_PAYLOAD,


    // Aviation related request payload types
    EMP_ISSUANCE_UKETS_REQUEST_PAYLOAD,
    
    EMP_VARIATION_UKETS_REQUEST_PAYLOAD,

    EMP_BATCH_REISSUE_REQUEST_PAYLOAD,

    AVIATION_AER_UKETS_REQUEST_PAYLOAD,
    AVIATION_DRE_UKETS_REQUEST_PAYLOAD,
    
    AVIATION_ACCOUNT_CLOSURE_REQUEST_PAYLOAD,

    WITHHOLDING_OF_ALLOWANCES_REQUEST_PAYLOAD,

    RETURN_OF_ALLOWANCES_REQUEST_PAYLOAD,

    EMP_ISSUANCE_CORSIA_REQUEST_PAYLOAD,
    EMP_VARIATION_CORSIA_REQUEST_PAYLOAD,
    
    AVIATION_AER_CORSIA_REQUEST_PAYLOAD,

    AVIATION_VIR_REQUEST_PAYLOAD,
}
