package uk.gov.pmrv.api.workflow.request.core.domain.enumeration;

public enum RequestCreateActionPayloadType {

    INSTALLATION_ACCOUNT_OPENING_SUBMIT_APPLICATION_PAYLOAD,
    PERMIT_BATCH_REISSUE_REQUEST_CREATE_ACTION_PAYLOAD,
    REPORT_RELATED_REQUEST_CREATE_ACTION_PAYLOAD,
    DOAL_REQUEST_CREATE_ACTION_PAYLOAD,
    EMP_BATCH_REISSUE_REQUEST_CREATE_ACTION_PAYLOAD,
    INSTALLATION_AUDIT_REQUEST_CREATE_ACTION_PAYLOAD,
    AVIATION_AER_CORSIA_ANNUAL_OFFSETTING_CREATE_ACTION_PAYLOAD,
    AVIATION_AER_CORSIA_3YEAR_PERIOD_OFFSETTING_CREATE_ACTION_PAYLOAD,
    EMPTY_PAYLOAD,
}
