package uk.gov.pmrv.api.workflow.request.core.domain.enumeration;

public enum RequestTaskPayloadType {

    INSTALLATION_ACCOUNT_OPENING_APPLICATION_PAYLOAD,
    INSTALLATION_ACCOUNT_TRANSFERRING_ARCHIVE_PAYLOAD,
    
    PERMIT_ISSUANCE_APPLICATION_SUBMIT_PAYLOAD,
    PERMIT_ISSUANCE_APPLICATION_REVIEW_PAYLOAD,
    PERMIT_ISSUANCE_APPLICATION_PEER_REVIEW_PAYLOAD,
    PERMIT_ISSUANCE_WAIT_FOR_PEER_REVIEW_PAYLOAD,
    PERMIT_ISSUANCE_APPLICATION_AMENDS_SUBMIT_PAYLOAD,
    PERMIT_ISSUANCE_WAIT_FOR_AMENDS_PAYLOAD,
    
    PERMIT_SURRENDER_APPLICATION_SUBMIT_PAYLOAD,
    PERMIT_SURRENDER_APPLICATION_REVIEW_PAYLOAD,
    PERMIT_SURRENDER_APPLICATION_PEER_REVIEW_PAYLOAD,
    PERMIT_SURRENDER_WAIT_FOR_PEER_REVIEW_PAYLOAD,
    PERMIT_SURRENDER_CESSATION_SUBMIT_PAYLOAD,
    
    PERMIT_REVOCATION_APPLICATION_SUBMIT_PAYLOAD,
    PERMIT_REVOCATION_APPLICATION_PEER_REVIEW_PAYLOAD,
    PERMIT_REVOCATION_WAIT_FOR_PEER_REVIEW_PAYLOAD,
    PERMIT_REVOCATION_WAIT_FOR_APPEAL_PAYLOAD,
    PERMIT_REVOCATION_CESSATION_SUBMIT_PAYLOAD,
    
    PERMIT_NOTIFICATION_APPLICATION_SUBMIT_PAYLOAD,
    PERMIT_NOTIFICATION_APPLICATION_REVIEW_PAYLOAD,
    PERMIT_NOTIFICATION_APPLICATION_PEER_REVIEW_PAYLOAD,
    PERMIT_NOTIFICATION_WAIT_FOR_PEER_REVIEW_PAYLOAD,
    PERMIT_NOTIFICATION_FOLLOW_UP_PAYLOAD,
    PERMIT_NOTIFICATION_WAIT_FOR_FOLLOW_UP_PAYLOAD,
    PERMIT_NOTIFICATION_FOLLOW_UP_APPLICATION_REVIEW_PAYLOAD,
    PERMIT_NOTIFICATION_FOLLOW_UP_APPLICATION_AMENDS_SUBMIT_PAYLOAD,
    PERMIT_NOTIFICATION_FOLLOW_UP_WAIT_FOR_AMENDS_PAYLOAD,

    PERMIT_VARIATION_APPLICATION_SUBMIT_PAYLOAD,
    PERMIT_VARIATION_APPLICATION_SUBMIT_REGULATOR_LED_PAYLOAD,
    PERMIT_VARIATION_APPLICATION_REVIEW_PAYLOAD,
    PERMIT_VARIATION_APPLICATION_PEER_REVIEW_PAYLOAD,
    PERMIT_VARIATION_APPLICATION_PEER_REVIEW_REGULATOR_LED_PAYLOAD,
    PERMIT_VARIATION_WAIT_FOR_PEER_REVIEW_PAYLOAD,
    PERMIT_VARIATION_WAIT_FOR_PEER_REVIEW_REGULATOR_LED_PAYLOAD,
    PERMIT_VARIATION_APPLICATION_AMENDS_SUBMIT_PAYLOAD,
    PERMIT_VARIATION_WAIT_FOR_AMENDS_PAYLOAD,
    
    PERMIT_TRANSFER_A_APPLICATION_SUBMIT_PAYLOAD,
    PERMIT_TRANSFER_B_APPLICATION_SUBMIT_PAYLOAD,
    PERMIT_TRANSFER_B_APPLICATION_REVIEW_PAYLOAD,
    PERMIT_TRANSFER_B_APPLICATION_PEER_REVIEW_PAYLOAD,
    PERMIT_TRANSFER_B_APPLICATION_AMENDS_SUBMIT_PAYLOAD,
    PERMIT_TRANSFER_B_WAIT_FOR_AMENDS_PAYLOAD,
    PERMIT_TRANSFER_B_WAIT_FOR_PEER_REVIEW_PAYLOAD,

    NON_COMPLIANCE_APPLICATION_SUBMIT_PAYLOAD,
    NON_COMPLIANCE_DAILY_PENALTY_NOTICE_PAYLOAD,
    NON_COMPLIANCE_DAILY_PENALTY_NOTICE_APPLICATION_PEER_REVIEW_PAYLOAD,
    NON_COMPLIANCE_DAILY_PENALTY_NOTICE_WAIT_FOR_PEER_REVIEW_PAYLOAD,
    NON_COMPLIANCE_NOTICE_OF_INTENT_PAYLOAD,
    NON_COMPLIANCE_NOTICE_OF_INTENT_APPLICATION_PEER_REVIEW_PAYLOAD,
    NON_COMPLIANCE_NOTICE_OF_INTENT_WAIT_FOR_PEER_REVIEW_PAYLOAD,
    NON_COMPLIANCE_CIVIL_PENALTY_PAYLOAD,
    NON_COMPLIANCE_CIVIL_PENALTY_APPLICATION_PEER_REVIEW_PAYLOAD,
    NON_COMPLIANCE_CIVIL_PENALTY_WAIT_FOR_PEER_REVIEW_PAYLOAD,
    NON_COMPLIANCE_FINAL_DETERMINATION_PAYLOAD,
    
    NER_APPLICATION_SUBMIT_PAYLOAD,
    NER_APPLICATION_REVIEW_PAYLOAD,
    NER_APPLICATION_PEER_REVIEW_PAYLOAD,
    NER_WAIT_FOR_PEER_REVIEW_PAYLOAD,
    NER_APPLICATION_AMENDS_SUBMIT_PAYLOAD,
    NER_WAIT_FOR_AMENDS_PAYLOAD,
    NER_AUTHORITY_RESPONSE_PAYLOAD,

    DOAL_APPLICATION_SUBMIT_PAYLOAD,
    DOAL_APPLICATION_PEER_REVIEW_PAYLOAD,
    DOAL_WAIT_FOR_PEER_REVIEW_PAYLOAD,
    DOAL_AUTHORITY_RESPONSE_PAYLOAD,
    
    AER_APPLICATION_SUBMIT_PAYLOAD,
    AER_APPLICATION_VERIFICATION_SUBMIT_PAYLOAD,
    AER_APPLICATION_REVIEW_PAYLOAD,
    AER_APPLICATION_AMENDS_SUBMIT_PAYLOAD,
    AER_WAIT_FOR_AMENDS_PAYLOAD,

    VIR_APPLICATION_SUBMIT_PAYLOAD,
    VIR_APPLICATION_REVIEW_PAYLOAD,
    VIR_RESPOND_TO_REGULATOR_COMMENTS_PAYLOAD,
    
    AIR_APPLICATION_SUBMIT_PAYLOAD,
    AIR_APPLICATION_REVIEW_PAYLOAD,
    AIR_RESPOND_TO_REGULATOR_COMMENTS_PAYLOAD,
    
    DRE_APPLICATION_SUBMIT_PAYLOAD,
    DRE_APPLICATION_PEER_REVIEW_PAYLOAD,
    DRE_WAIT_FOR_PEER_REVIEW_PAYLOAD,
    
    RFI_RESPONSE_SUBMIT_PAYLOAD,
    
    RDE_RESPONSE_SUBMIT_PAYLOAD,
    RDE_WAIT_FOR_RESPONSE_PAYLOAD,

    PAYMENT_MAKE_PAYLOAD,
    PAYMENT_TRACK_PAYLOAD,
    PAYMENT_CONFIRM_PAYLOAD,

    SYSTEM_MESSAGE_NOTIFICATION_PAYLOAD,

    WITHHOLDING_OF_ALLOWANCES_APPLICATION_SUBMIT_PAYLOAD,

    WITHHOLDING_OF_ALLOWANCES_WAIT_FOR_PEER_REVIEW_PAYLOAD,

    WITHHOLDING_OF_ALLOWANCES_APPLICATION_PEER_REVIEW_PAYLOAD,

    WITHHOLDING_OF_ALLOWANCES_WITHDRAWAL_APPLICATION_SUBMIT_PAYLOAD,

    RETURN_OF_ALLOWANCES_APPLICATION_SUBMIT_PAYLOAD,

    RETURN_OF_ALLOWANCES_RETURNED_APPLICATION_SUBMIT_PAYLOAD,
    RETURN_OF_ALLOWANCES_WAIT_FOR_PEER_REVIEW_PAYLOAD,
    RETURN_OF_ALLOWANCES_APPLICATION_PEER_REVIEW_PAYLOAD,


    //aviation related request task payload types
    EMP_ISSUANCE_UKETS_APPLICATION_SUBMIT_PAYLOAD,
    EMP_ISSUANCE_UKETS_APPLICATION_REVIEW_PAYLOAD,
    EMP_ISSUANCE_UKETS_APPLICATION_PEER_REVIEW_PAYLOAD,
    EMP_ISSUANCE_UKETS_WAIT_FOR_PEER_REVIEW_PAYLOAD,
    EMP_ISSUANCE_UKETS_APPLICATION_AMENDS_SUBMIT_PAYLOAD,
    EMP_ISSUANCE_UKETS_WAIT_FOR_AMENDS_PAYLOAD,
    
    EMP_VARIATION_UKETS_APPLICATION_SUBMIT_PAYLOAD,
    EMP_VARIATION_UKETS_APPLICATION_SUBMIT_REGULATOR_LED_PAYLOAD,
    EMP_VARIATION_UKETS_APPLICATION_REVIEW_PAYLOAD,
    EMP_VARIATION_UKETS_APPLICATION_PEER_REVIEW_PAYLOAD,
    EMP_VARIATION_UKETS_APPLICATION_PEER_REVIEW_REGULATOR_LED_PAYLOAD,
    EMP_VARIATION_UKETS_WAIT_FOR_PEER_REVIEW_PAYLOAD,
    EMP_VARIATION_UKETS_WAIT_FOR_PEER_REVIEW_REGULATOR_LED_PAYLOAD,
    EMP_VARIATION_UKETS_APPLICATION_AMENDS_SUBMIT_PAYLOAD,
    EMP_VARIATION_UKETS_WAIT_FOR_AMENDS_PAYLOAD,

    AVIATION_AER_UKETS_APPLICATION_SUBMIT_PAYLOAD,
    AVIATION_AER_UKETS_APPLICATION_VERIFICATION_SUBMIT_PAYLOAD,
    AVIATION_AER_UKETS_APPLICATION_REVIEW_PAYLOAD,
    AVIATION_AER_UKETS_APPLICATION_AMENDS_SUBMIT_PAYLOAD,
    AVIATION_AER_UKETS_WAIT_FOR_AMENDS_PAYLOAD,

    AVIATION_DRE_UKETS_APPLICATION_SUBMIT_PAYLOAD,
    AVIATION_DRE_UKETS_APPLICATION_PEER_REVIEW_PAYLOAD,
    AVIATION_DRE_UKETS_WAIT_FOR_PEER_REVIEW_PAYLOAD,

    AVIATION_VIR_APPLICATION_SUBMIT_PAYLOAD,
    AVIATION_VIR_APPLICATION_REVIEW_PAYLOAD,
    AVIATION_VIR_RESPOND_TO_REGULATOR_COMMENTS_PAYLOAD,

    AVIATION_ACCOUNT_CLOSURE_SUBMIT_PAYLOAD,

    EMP_ISSUANCE_CORSIA_APPLICATION_SUBMIT_PAYLOAD,
    EMP_ISSUANCE_CORSIA_APPLICATION_REVIEW_PAYLOAD,
    EMP_ISSUANCE_CORSIA_APPLICATION_PEER_REVIEW_PAYLOAD,
    EMP_ISSUANCE_CORSIA_WAIT_FOR_PEER_REVIEW_PAYLOAD,
    EMP_ISSUANCE_CORSIA_APPLICATION_AMENDS_SUBMIT_PAYLOAD,
    EMP_ISSUANCE_CORSIA_WAIT_FOR_AMENDS_PAYLOAD,

    EMP_VARIATION_CORSIA_APPLICATION_SUBMIT_PAYLOAD,
    EMP_VARIATION_CORSIA_APPLICATION_REVIEW_PAYLOAD,
    EMP_VARIATION_CORSIA_APPLICATION_PEER_REVIEW_PAYLOAD,
    EMP_VARIATION_CORSIA_WAIT_FOR_PEER_REVIEW_PAYLOAD,
    EMP_VARIATION_CORSIA_APPLICATION_AMENDS_SUBMIT_PAYLOAD,
    EMP_VARIATION_CORSIA_WAIT_FOR_AMENDS_PAYLOAD,

    EMP_VARIATION_CORSIA_APPLICATION_SUBMIT_REGULATOR_LED_PAYLOAD,
    EMP_VARIATION_CORSIA_APPLICATION_PEER_REVIEW_REGULATOR_LED_PAYLOAD,
    EMP_VARIATION_CORSIA_WAIT_FOR_PEER_REVIEW_REGULATOR_LED_PAYLOAD,
    

    AVIATION_AER_CORSIA_APPLICATION_SUBMIT_PAYLOAD,
    AVIATION_AER_CORSIA_APPLICATION_VERIFICATION_SUBMIT_PAYLOAD,
    AVIATION_AER_CORSIA_APPLICATION_REVIEW_PAYLOAD,
    AVIATION_AER_CORSIA_APPLICATION_AMENDS_SUBMIT_PAYLOAD,
    AVIATION_AER_CORSIA_WAIT_FOR_AMENDS_PAYLOAD,
}
