import { RequestTaskActionProcessDTO, RequestTaskDTO } from 'pmrv-api';

export const cancelActionMap: Partial<
  Record<RequestTaskDTO['type'], RequestTaskActionProcessDTO['requestTaskActionType']>
> = {
  AVIATION_ACCOUNT_CLOSURE_SUBMIT: 'AVIATION_ACCOUNT_CLOSURE_CANCEL_APPLICATION',
  AVIATION_DRE_UKETS_APPLICATION_SUBMIT: 'AVIATION_DRE_CANCEL_APPLICATION',
  EMP_VARIATION_UKETS_APPLICATION_SUBMIT: 'EMP_VARIATION_CANCEL_APPLICATION',
  EMP_VARIATION_CORSIA_APPLICATION_SUBMIT: 'EMP_VARIATION_CANCEL_APPLICATION',
  EMP_VARIATION_UKETS_REGULATOR_LED_APPLICATION_SUBMIT: 'EMP_VARIATION_CANCEL_APPLICATION',
  EMP_VARIATION_CORSIA_REGULATOR_LED_APPLICATION_SUBMIT: 'EMP_VARIATION_CANCEL_APPLICATION',
  AVIATION_AER_CORSIA_ANNUAL_OFFSETTING_APPLICATION_SUBMIT: 'AVIATION_AER_CORSIA_ANNUAL_OFFSETTING_CANCEL_APPLICATION',
  AVIATION_AER_CORSIA_3YEAR_PERIOD_OFFSETTING_APPLICATION_SUBMIT:
    'AVIATION_AER_CORSIA_3YEAR_PERIOD_OFFSETTING_CANCEL_APPLICATION',
  AVIATION_DOE_CORSIA_APPLICATION_SUBMIT: 'AVIATION_DOE_CORSIA_SUBMIT_CANCEL',
};
