package uk.gov.pmrv.api.permit.domain.sourcestreams;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum SourceStreamDescription {

    ACETYLENE("Acetylene"),
    ANTHRACITE("Anthracite"),
    BIODIESELS("Biodiesels"),
    BIOGASOLINE("Biogasoline"),
    BIOMASS("Biomass"),
    BITUMEN("Bitumen"),
    BLAST_FURNACE_GAS("Blast Furnace Gas"),
    BLENDED_FUEL_GAS("Blended Fuel Gas"),
    CARBON_MONOXIDE("Carbon Monoxide"),
    CHARCOAL("Charcoal"),
    COAL("Coal"),
    COAL_TAR("Coal Tar"),
    COKE("Coke"),
    COKE_OVEN_COKE_LIGNITE_COKE("Coke Oven Coke & Lignite Coke"),
    COKE_OVEN_GAS("Coke Oven Gas"),
    COKING_COAL("Coking Coal"),
    COLLIERY_METHANE("Colliery Methane"),
    CRUDE_OIL("Crude Oil"),
    ETHANE("Ethane"),
    FUEL_GAS("Fuel Gas"),
    FUEL_OIL("Fuel Oil"),
    GAS_COKE("Gas Coke"),
    GAS_DIESEL_OIL("Gas/Diesel Oil"),
    GAS_OIL("Gas/Oil"),
    GAS_WORKS("Gas Works"),
    HIGH_PRESSURE_FLARE_GAS("High Pressure Flare Gas"),
    IMPORT_FUEL_GAS("Import Fuel Gas"),
    INDUSTRIAL_WASTES("Industrial Wastes"),
    KEROSENE_OTHER_THAN_JET_KEROSENE("Kerosene (other than jet kerosene)"),
    LANDFILL_GAS("Landfill Gas"),
    LIGNITE("Lignite"),
    LIQUEFIED_PETROLEUM_GASES("Liquefied Petroleum Gases"),
    LOW_LOW_PRESSURE_FLARE_GAS("Low Low Pressure Flare Gas"),
    LOW_PRESSURE_FLARE_GAS("Low Pressure Flare Gas"),
    LUBRICANTS("Lubricants"),
    MATERIAL("Material"),
    MEDIUM_PRESSURE_FLARE_GAS("Medium Pressure Flare Gas"),
    METHANE("Methane"),
    MOTOR_GASOLINE("Motor Gsoline"),
    MSW("MSW"),
    NAPHTHA("Naphtha"),
    NATURAL_GAS("Natural Gas"),
    NATURAL_GAS_LIQUIDS("Natural Gas Liquids"),
    NON_BIOMASS_PACKAGING_WASTE("Non-biomass Packaging Waste"),
    OIL_SHALE_AND_TAR_SANDS("Oil Shale and Tar Sands"),
    OPG("OPG"),
    ORIMULSION("Orimulsion"),
    OTHER("Other"),
    OTHER_BIOGAS("Other Biogas"),
    OTHER_BITUMINOUS_COAL("Other Bituminous Coal"),
    OTHER_LIQUID_BIOFUELS("Other Liquid Biofuels"),
    OTHER_PETROLEUM_PRODUCTS("Other Petroleum Products"),
    OTHER_PRIMARY_SOLID_BIOMASS("Other Primary Solid Biomass"),
    OXYGEN_STEEL_FURNACE_GAS("Oxygen Steel Furnace Gas"),
    PARAFFIN_WAXES("Paraffin Waxes"),
    PATENT_FUEL("Patent Fuel"),
    PEAT("Peat"),
    PETROL("Petrol"),
    PETROLEUM_COKE("Petroleum Coke"),
    PILOT_AND_PURGE_FLARE_GAS("Pilot and Purge Flare Gas"),
    PILOT_FLARE_GAS("Pilot Flare Gas"),
    PROPANE("Propane"),
    REFINERY_FEEDSTOCKS("Refinery Feedstocks"),
    REFINERY_GAS("Refinery Gas"),
    RESIDUAL_FUEL_OIL("Residual Fuel Oil"),
    SCRAP_TYRES("Scrap Tyres"),
    SHALE_OIL("Shale Oil"),
    SLUDGE_GAS("Sludge Gas"),
    SOUR_GAS("Sour Gas"),
    SOUR_GAS_FLARE("Sour Gas Flare"),
    SSF("SSF"),
    SUB_BITUMINOUS_COAL("Sub-Bituminous Coal"),
    WASTE_OILS("Waste Oils"),
    WASTE_SOLVENTS("Waste Solvents"),
    WASTE_TYRES("Waste Tyres"),
    WHITE_SPIRIT_SBP("White Spirit & SBP"),
    WOOD_WOOD_WASTE("Wood/Wood Waste");

    private String description;
}
