import { RequestDetailsDTO } from 'pmrv-api';

export const workflowDetailsTypesMap: Partial<Record<RequestDetailsDTO['requestType'], string>> = {
  INSTALLATION_ACCOUNT_OPENING: 'Account creation',
  PERMIT_ISSUANCE: 'Permit application',
  PERMIT_SURRENDER: 'Permit surrender',
  PERMIT_TRANSFER_A: 'Permit transfer',
  PERMIT_TRANSFER_B: 'Permit transfer',
  PERMIT_VARIATION: 'Permit variation',
  PERMIT_REVOCATION: 'Permit revocation',
  PERMIT_NOTIFICATION: 'Permit notification',
  PERMIT_BATCH_REISSUE: 'Batch variation',
  AER: 'emissions report',
  AVIATION_AER_CORSIA: 'emissions report',
  DRE: 'determination of reportable emissions',
  VIR: 'verifier improvement report',
  AIR: 'annual improvement report',
  DOAL: 'Determination of activity level',
  NON_COMPLIANCE: 'Non-compliance',
  EMP_ISSUANCE_UKETS: 'Emissions monitoring plan',
  AVIATION_AER_UKETS: 'Annual emissions',
  AVIATION_DRE_UKETS: 'determination of emissions',
  AVIATION_ACCOUNT_CLOSURE: 'Account closure',
  EMP_VARIATION_UKETS: 'EMP variation',
  WITHHOLDING_OF_ALLOWANCES: 'Withholding of allowances',
  RETURN_OF_ALLOWANCES: 'Return of allowances',
  AVIATION_NON_COMPLIANCE: 'Non-compliance',
  EMP_VARIATION_CORSIA: 'EMP variation',
  AVIATION_VIR: 'verifier improvement report',
};
