export enum AirportTypes {
  UKETS_FLIGHTS_TO_EEA_REPORTED = 'UKETS_FLIGHTS_TO_EEA_REPORTED',
  UKETS_FLIGHTS_TO_EEA_NOT_REPORTED = 'UKETS_FLIGHTS_TO_EEA_NOT_REPORTED',
  EEA_COUNTRY = 'EEA_COUNTRY',
  EFTA_COUNTRY = 'EFTA_COUNTRY',
}
