package uk.gov.pmrv.api.workflow.request.flow.common.service.notification;

public enum DocumentTemplateGenerationContextActionType {
    
    RFI_SUBMIT,
    RDE_SUBMIT,

    PERMIT_ISSUANCE_GHGE_GRANTED,
    PERMIT_ISSUANCE_HSE_GRANTED,
    PERMIT_ISSUANCE_WASTE_GRANTED,
    PERMIT_ISSUANCE_REJECTED,
    PERMIT_ISSUANCE_DEEMED_WITHDRAWN,
    
    PERMIT_SURRENDER_GRANTED,
    PERMIT_SURRENDER_REJECTED,
    PERMIT_SURRENDER_DEEMED_WITHDRAWN,
    PERMIT_SURRENDER_CESSATION,
    
    PERMIT_REVOCATION,
    PERMIT_REVOCATION_WITHDRAWN,
    PERMIT_REVOCATION_CESSATION,

    PERMIT_NOTIFICATION_GRANTED,
    PERMIT_NOTIFICATION_REJECTED,
    
    PERMIT_VARIATION_GRANTED,
    PERMIT_VARIATION_REJECTED,
    PERMIT_VARIATION_REGULATOR_LED_APPROVED,

    PERMIT_TRANSFER_A_ACCEPTED,
    PERMIT_TRANSFER_A_REFUSED,
    PERMIT_TRANSFER_A_DEEMED_WITHDRAWN,
    
    PERMIT_TRANSFER_B_ACCEPTED,
    PERMIT_TRANSFER_B_REFUSED,
    PERMIT_TRANSFER_B_DEEMED_WITHDRAWN,

    PERMANENT_CESSATION_SUBMITTED,
    
    DOAL_SUBMITTED,
    DOAL_ACCEPTED,
    DOAL_REJECTED,
    
    DRE_SUBMIT,

    VIR_REVIEWED,

    AIR_REVIEWED,

    WITHHOLDING_OF_ALLOWANCES,

    WITHHOLDING_OF_ALLOWANCES_WITHDRAWN,

    RETURN_OF_ALLOWANCES,

    INSTALLATION_ONSITE_INSPECTION_SUBMITTED,
    INSTALLATION_AUDIT_SUBMITTED,

    AVIATION_DRE_SUBMIT,
    AVIATION_DOE_SUBMIT,

    AVIATION_VIR_REVIEWED,
    
    REISSUE,

    EMP_ISSUANCE_GRANTED,
    EMP_ISSUANCE_DEEMED_WITHDRAWN,
    
    EMP_VARIATION_ACCEPTED,
    EMP_VARIATION_REJECTED,
    EMP_VARIATION_REGULATOR_LED_APPROVED,

    EMP_ISSUANCE_CORSIA_GRANTED,
    EMP_ISSUANCE_CORSIA_DEEMED_WITHDRAWN,
    
    EMP_VARIATION_CORSIA_REGULATOR_LED_APPROVED,

    EMP_VARIATION_CORSIA_ACCEPTED,
    EMP_VARIATION_CORSIA_REJECTED,

    AVIATION_AER_CORSIA_ANNUAL_OFFSETTING_SUBMITTED,
    AVIATION_AER_CORSIA_3_YEAR_PERIOD_OFFSETTING_SUBMITTED
}
