import { RequestTaskDTO } from 'pmrv-api';

export const EMP_SUBMIT_TASK_TYPES: RequestTaskDTO['type'][] = [
  'EMP_ISSUANCE_UKETS_APPLICATION_SUBMIT',
  'EMP_ISSUANCE_CORSIA_APPLICATION_SUBMIT',
  'EMP_ISSUANCE_UKETS_APPLICATION_AMENDS_SUBMIT',
  'EMP_ISSUANCE_CORSIA_APPLICATION_AMENDS_SUBMIT',
  'EMP_VARIATION_UKETS_APPLICATION_AMENDS_SUBMIT',
  'EMP_VARIATION_CORSIA_APPLICATION_AMENDS_SUBMIT',
];
export const VARIATION_OPERATOR_LED_SUBMIT_TASK_TYPES: RequestTaskDTO['type'][] = [
  'EMP_VARIATION_UKETS_APPLICATION_SUBMIT',
  'EMP_VARIATION_CORSIA_APPLICATION_SUBMIT',
];
