import { RequestTaskDTO } from 'pmrv-api';

export const waitForRfiRdeTypes: Array<RequestTaskDTO['type']> = [
  'PERMIT_ISSUANCE_WAIT_FOR_RFI_RESPONSE',
  'PERMIT_ISSUANCE_WAIT_FOR_RDE_RESPONSE',
  'PERMIT_SURRENDER_WAIT_FOR_RFI_RESPONSE',
  'PERMIT_SURRENDER_WAIT_FOR_RDE_RESPONSE',
  'PERMIT_NOTIFICATION_WAIT_FOR_RFI_RESPONSE',
  'PERMIT_VARIATION_WAIT_FOR_RFI_RESPONSE',
  'PERMIT_VARIATION_WAIT_FOR_RDE_RESPONSE',
  'PERMIT_TRANSFER_B_WAIT_FOR_RFI_RESPONSE',
  'PERMIT_TRANSFER_B_WAIT_FOR_RDE_RESPONSE',
  'VIR_WAIT_FOR_RFI_RESPONSE',
  'AIR_WAIT_FOR_RFI_RESPONSE',
  'EMP_ISSUANCE_UKETS_WAIT_FOR_RFI_RESPONSE',
  'EMP_ISSUANCE_CORSIA_WAIT_FOR_RFI_RESPONSE',
  'EMP_ISSUANCE_UKETS_WAIT_FOR_RDE_RESPONSE',
  'EMP_ISSUANCE_CORSIA_WAIT_FOR_RDE_RESPONSE',
  'EMP_VARIATION_UKETS_WAIT_FOR_RFI_RESPONSE',
  'EMP_VARIATION_UKETS_WAIT_FOR_RDE_RESPONSE',
  'EMP_VARIATION_CORSIA_WAIT_FOR_RFI_RESPONSE',
  'EMP_VARIATION_CORSIA_WAIT_FOR_RDE_RESPONSE',
  'AVIATION_VIR_WAIT_FOR_RFI_RESPONSE',
  // add here the rest of the workflow cases
];
