import { RequestTaskActionProcessDTO, RequestTaskDTO } from 'pmrv-api';

export const sendPeerReviewMap: Partial<
  Record<RequestTaskDTO['type'], RequestTaskActionProcessDTO['requestTaskActionType']>
> = {
  INSTALLATION_AUDIT_APPLICATION_SUBMIT: 'INSTALLATION_AUDIT_REQUEST_PEER_REVIEW',
  INSTALLATION_ONSITE_INSPECTION_APPLICATION_SUBMIT: 'INSTALLATION_ONSITE_INSPECTION_REQUEST_PEER_REVIEW',
};

export const notifyOperatorMap: Partial<
  Record<RequestTaskDTO['type'], RequestTaskActionProcessDTO['requestTaskActionType']>
> = {
  INSTALLATION_AUDIT_APPLICATION_SUBMIT: 'INSTALLATION_AUDIT_SUBMIT_NOTIFY_OPERATOR',
  INSTALLATION_ONSITE_INSPECTION_APPLICATION_SUBMIT: 'INSTALLATION_ONSITE_INSPECTION_SUBMIT_NOTIFY_OPERATOR',
};

export const peerReviewDecisionMap: Partial<
  Record<RequestTaskDTO['type'], RequestTaskActionProcessDTO['requestTaskActionType']>
> = {
  INSTALLATION_AUDIT_APPLICATION_PEER_REVIEW: 'INSTALLATION_AUDIT_SUBMIT_PEER_REVIEW_DECISION',
  INSTALLATION_ONSITE_INSPECTION_APPLICATION_PEER_REVIEW: 'INSTALLATION_ONSITE_INSPECTION_SUBMIT_PEER_REVIEW_DECISION',
};

export const isWaitForPeerReviewTask: Array<RequestTaskDTO['type']> = [
  'INSTALLATION_AUDIT_WAIT_FOR_PEER_REVIEW',
  'INSTALLATION_ONSITE_INSPECTION_WAIT_FOR_PEER_REVIEW',
];
