import { MaterialityLevel } from 'pmrv-api';

export const ukEtsVerificationConductAccreditedVerifiers: MaterialityLevel['accreditationReferenceDocumentTypes'] = [
  'UK_ETS_VERIFICATION_CONDUCT_ACCREDITED_VER_SI_2020_1265',
  'UK_ETS_VERIFICATION_CONDUCT_ACCREDITED_VER_REGULATION_EU_2018_2067',
  'UK_ETS_VERIFICATION_CONDUCT_ACCREDITED_VER_ISO_14065_2020',
  'UK_ETS_VERIFICATION_CONDUCT_ACCREDITED_VER_ISO_14064_3_2019',
  'UK_ETS_VERIFICATION_CONDUCT_ACCREDITED_VER_MD_6_2014',
  'UK_ETS_VERIFICATION_CONDUCT_ACCREDITED_VER_GUIDANCE_AUTHORITY_MONITORING_REPORTING_REGULATION',
  'UK_ETS_VERIFICATION_CONDUCT_ACCREDITED_VER_GUIDANCE_EUROPEAN_COMISSION_UK_ETS_ORDER',
];

export const ukEtsVerificationConductAccreditedVerifiersAndAssuranceProviders: MaterialityLevel['accreditationReferenceDocumentTypes'] =
  [
    'UK_ETS_VERIFICATION_CONDUCT_ACCREDITED_VER_AND_PROVIDERS_3000',
    'UK_ETS_VERIFICATION_CONDUCT_ACCREDITED_VER_AND_PROVIDERS_3410',
  ];

export const ukEtsVerificationRules: MaterialityLevel['accreditationReferenceDocumentTypes'] = [
  'UK_ETS_VERIFICATION_RULE_ORDER_2020_1265',
  'UK_ETS_VERIFICATION_RULE_ORDER_2020_1557',
  'UK_ETS_VERIFICATION_RULE_EU_REGULATION_2018_2067',
  'UK_ETS_VERIFICATION_RULE_EU_REGULATION_2018_2066',
  'UK_ETS_VERIFICATION_RULE_GUIDANCE_EUROPEAN_COMISSION_UK_ETS_ORDER',
];

export const euEtsVerificationConductAccreditedVerifiers: MaterialityLevel['accreditationReferenceDocumentTypes'] = [
  'EU_ETS_VERIFICATION_CONDUCT_ACCREDITED_VER_REGULATION_EU_2018_2067',
  'EU_ETS_VERIFICATION_CONDUCT_ACCREDITED_VER_ISO_14065_2020',
  'EU_ETS_VERIFICATION_CONDUCT_ACCREDITED_VER_ISO_14064_3_2019',
  'EU_ETS_VERIFICATION_CONDUCT_ACCREDITED_VER_MD_6_2014',
  'EU_ETS_VERIFICATION_CONDUCT_ACCREDITED_VER_GUIDANCE_EUROPEAN_COMISSION_FOR_VER_ACCREDIATION',
  'EU_ETS_VERIFICATION_CONDUCT_ACCREDITED_VER_EA_6_03',
];

export const euEtsVerificationConductAccreditedVerifiersAndAssuranceProviders: MaterialityLevel['accreditationReferenceDocumentTypes'] =
  [
    'EU_ETS_VERIFICATION_CONDUCT_ACCREDITED_VER_AND_PROVIDERS_3000',
    'EU_ETS_VERIFICATION_CONDUCT_ACCREDITED_VER_AND_PROVIDERS_3410',
  ];

export const euEtsVerificationRules: MaterialityLevel['accreditationReferenceDocumentTypes'] = [
  'EU_ETS_VERIFICATION_RULE_EU_REGULATION_2018_2066',
  'EU_ETS_VERIFICATION_RULE_GUIDANCE_EUROPEAN_COMISSION_MONITORING_REPORTING_REGULATION',
  'EU_ETS_VERIFICATION_RULE_GUIDANCE_EUROPEAN_COMISSION_ACCREDITATION_VER_REGULATION',
];
